Repository pimcore/studio-backend-bundle, pull requests merged in 2024-11, with the labels that each got.

#521 [Workflows] Add new property to indicate if workflow is available to detail endpoints
  src/Asset/Schema/Asset.php
  src/Asset/Service/AssetService.php
  src/Asset/Service/AssetServiceInterface.php
  src/DataObject/Schema/DataObject.php
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataObjectServiceInterface.php
  src/Document/Schema/Document.php
  src/Document/Service/DocumentService.php
  src/Document/Service/DocumentServiceInterface.php
  src/Grid/Column/Resolver/Metadata/AssetResolver.php
  src/Grid/Column/Resolver/Metadata/DocumentResolver.php
  src/Util/Trait/WorkflowAvailableTrait.php
  src/Workflow/Service/WorkflowDetailsService.php
  src/Workflow/Service/WorkflowDetailsServiceInterface.php
Labels: Improvement

#526 [Task] Add admin flag to user schema
  src/User/Hydrator/UserHydrator.php
  src/User/Schema/User.php
Labels: Task

#532 [DataObject]: Apply dynamic data to data object layout endpoint
  src/Asset/Service/AssetService.php
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/LayoutService.php
Labels: Improvement

#535 [Grid] [Filter] Add filter for system.id
  config/data_index_filters.yaml
  config/grid.yaml
  doc/03_Grid.md
  src/DataIndex/Filter/IdFilter.php
  src/Grid/Column/ColumnType.php
  src/Grid/Column/Definition/System/IdDefinition.php
  src/Grid/Mapper/ColumnMapper.php
  tests/Unit/Grid/Mapper/ColumnMapperTest.php
  tests/Unit/Grid/Service/SystemColumnServiceTest.php
Labels: Improvement

#537 [Grid] [Filter] Add filter for system.integer
  config/data_index_filters.yaml
  doc/03_Grid.md
  src/DataIndex/Filter/IntegerFilter.php
  src/DataIndex/Query/AssetQuery.php
  src/DataIndex/Query/DataObjectQuery.php
  src/DataIndex/Query/DocumentQuery.php
  src/DataIndex/Query/QueryInterface.php
Labels: Improvement

#541 [Grid] Add ID Resolver
  config/grid.yaml
  src/Grid/Column/Resolver/System/IdResolver.php
Labels: Improvement

#542 [Task] Add listener to enable options like in Classic UI
  config/event_subscribers.yaml
  src/DataObject/Data/Adapter/ReverseObjectRelationAdapter.php
  src/EventSubscriber/ApiContextSubscriber.php
Labels: Task

#545 Extend current-user-information endpoint
  config/users.yaml
  src/Authorization/Controller/LoginController.php
  src/OpenApi/Schema/UserInformation.php
  src/User/Controller/CurrentUserController.php
  src/User/Event/UserInformationEvent.php
  src/User/Hydrator/UserInformationHydrator.php
  src/User/Hydrator/UserInformationHydratorInterface.php
  src/User/Service/UserInformationService.php
  src/User/Service/UserInformationServiceInterface.php
Labels: Improvement

#548 Add available admin languages
  src/Setting/Provider/SystemSettingsProvider.php
Labels: Task, Pimcore:ToDo

#552 [User Management] Add user Search
  config/users.yaml
  src/User/Controller/SearchUserController.php
  src/User/Hydrator/SimpleUserHydrator.php
  src/User/Hydrator/SimpleUserHydratorInterface.php
  src/User/Repository/UserRepository.php
  src/User/Repository/UserRepositoryInterface.php
  src/User/Service/UserService.php
  src/User/Service/UserServiceInterface.php
  tests/Unit/User/Service/UserServiceTest.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#557 Fix isAdmin property in schema.
  src/OpenApi/Schema/UserInformation.php
Labels: Improvement

#556 [User Management] Add Dependencies to User.
  config/users.yaml
  src/User/Hydrator/DependencyHydrator.php
  src/User/Hydrator/DependencyHydratorInterface.php
  src/User/Hydrator/UserHydrator.php
  src/User/Schema/Dependency.php
  src/User/Schema/ObjectDependencies.php
  src/User/Schema/User.php
  src/User/Service/ObjectDependenciesService.php
  src/User/Service/ObjectDependenciesServiceInterface.php
  tests/Unit/User/Service/ObjectDependenciesServiceTest.php
Labels: Improvement

#561 [User Management] Add default key bindings Endpoint
  README.md
  config/pimcore/config.yaml
  config/pimcore/user_key_binding.yaml
  config/users.yaml
  doc/07_User.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/User/Controller/GetDefaultKeyBindingsController.php
  src/User/Hydrator/KeyBindingHydrator.php
  src/User/Hydrator/KeyBindingHydratorInterface.php
  src/User/Hydrator/UserHydrator.php
  src/User/Service/KeyBindingService.php
  src/User/Service/KeyBindingServiceInterface.php
  tests/Unit/User/Hydrator/KeyBindingHydratorTest.php
  tests/Unit/User/Service/KeyBindingServiceTest.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#567 [ColumnFilter] Trim whitespace for filterValue
  src/MappedParameter/Filter/SimpleColumnFilter.php
  tests/Unit/MappedParameter/Filter/SimpleColumnFilterTest.php
Labels: Improvement

#573 [Task] Add check for default metadata on patch
  src/Asset/Patcher/Adapter/MetadataAdapter.php
Labels: Task

#576 Update to static resolver 2.x
  composer.json
Labels: Task

#578 [Data Object Editor] Add normalizer for all field types
  config/data_objects.yaml
  config/updater.yaml
  src/Asset/Service/AssetService.php
  src/DataObject/Data/Adapter/BlockAdapter.php
  src/DataObject/Data/Adapter/ClassificationStoreAdapter.php
  src/DataObject/Data/Adapter/FieldCollectionsAdapter.php
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
  src/DataObject/Data/Adapter/ManyToManyRelationAdapter.php
  src/DataObject/Data/Adapter/ObjectBricksAdapter.php
  src/DataObject/Data/ClassData.php
  src/DataObject/Data/DataNormalizerInterface.php
  src/DataObject/Data/RelationData.php
  src/DataObject/Schema/DataObject.php
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataObjectServiceInterface.php
  src/DataObject/Service/DataService.php
  src/DataObject/Service/DataServiceInterface.php
  src/DataObject/Util/Trait/ClassDataTrait.php
  src/Document/Service/DocumentService.php
  src/Exception/Api/InvalidDataTypeException.php
  src/Grid/Column/Resolver/Metadata/DataObjectResolver.php
  src/Workflow/Service/WorkflowDetailsService.php
  src/Workflow/Service/WorkflowDetailsServiceInterface.php
Labels: New Feature

#581 [Data Object Editor] Add Endpoint to get fieldcollection
  config/class.yaml
  src/Class/Controller/FieldCollection/LayoutController.php
  src/Class/Event/FieldCollection/LayoutDefinitionEvent.php
  src/Class/Hydrator/FieldCollection/LayoutDefinitionHydrator.php
  src/Class/Hydrator/FieldCollection/LayoutDefinitionHydratorInterface.php
  src/Class/Schema/LayoutDefinition.php
  src/Class/Service/FieldCollection/LayoutDefinitionService.php
  src/Class/Service/FieldCollection/LayoutDefinitionServiceInterface.php
  src/OpenApi/Config/Tags.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#582 [Quantity value] Add endpoints for units
  config/class.yaml
  src/Class/Attribute/Request/ConvertRequestBody.php
  src/Class/Attribute/Response/ConvertedValueJson.php
  src/Class/Attribute/Response/QuantityValueUnitsJson.php
  src/Class/Controller/QuantityValue/ConvertAllController.php
  src/Class/Controller/QuantityValue/ConvertController.php
  src/Class/Controller/QuantityValue/UnitListController.php
  src/Class/Event/PreResponse/QuantityValueConversionEvent.php
  src/Class/Event/PreResponse/QuantityValueUnitEvent.php
  src/Class/Repository/QuantityValueRepository.php
  src/Class/Repository/QuantityValueRepositoryInterface.php
  src/Class/Schema/ConvertAllParameters.php
  src/Class/Schema/ConvertParameters.php
  src/Class/Schema/ConvertedQuantityValue.php
  src/Class/Schema/ConvertedQuantityValues.php
  src/Class/Schema/QuantityValueUnit.php
  src/Class/Service/QuantityValueService.php
  src/Class/Service/QuantityValueServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#583 [Improvement]: Ignore undefined data object adapters for now
  src/DataObject/Data/Adapter/BlockAdapter.php
  src/DataObject/Data/Adapter/ClassificationStoreAdapter.php
  src/DataObject/Data/Adapter/EncryptedFieldAdapter.php
  src/DataObject/Data/Adapter/FieldCollectionsAdapter.php
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
  src/DataObject/Data/Adapter/ObjectBricksAdapter.php
  src/DataObject/Service/DataAdapterService.php
  src/DataObject/Service/DataAdapterServiceInterface.php
  src/DataObject/Service/DataService.php
  src/DataObject/Service/Loader/TaggedIteratorDataAdapter.php
  src/DataObject/Util/Trait/ValidateFieldTypeTrait.php
  src/Updater/Service/UpdateService.php
Labels: Improvement

#591 [Data Object Editor]: Resolve normalizer issues
  src/DataObject/Data/Adapter/AdvancedManyToManyObjectRelationAdapter.php
  src/DataObject/Data/Adapter/AdvancedManyToManyRelationAdapter.php
  src/DataObject/Data/Adapter/BlockAdapter.php
  src/DataObject/Data/Adapter/BooleanAdapter.php
  src/DataObject/Data/Adapter/CalculatedValueAdapter.php
  src/DataObject/Data/Adapter/CheckboxAdapter.php
  src/DataObject/Data/Adapter/ClassificationStoreAdapter.php
  src/DataObject/Data/Adapter/ConsentAdapter.php
  src/DataObject/Data/Adapter/DateAdapter.php
  src/DataObject/Data/Adapter/DateRangeAdapter.php
  src/DataObject/Data/Adapter/EncryptedFieldAdapter.php
  src/DataObject/Data/Adapter/ExternalImageAdapter.php
  src/DataObject/Data/Adapter/FieldCollectionsAdapter.php
  src/DataObject/Data/Adapter/GeoBoundsAdapter.php
  src/DataObject/Data/Adapter/GeoPointAdapter.php
  src/DataObject/Data/Adapter/GeoPointsAdapter.php
  src/DataObject/Data/Adapter/HotspotImageAdapter.php
  src/DataObject/Data/Adapter/ImageAdapter.php
  src/DataObject/Data/Adapter/ImageGalleryAdapter.php
  src/DataObject/Data/Adapter/InputQuantityValueAdapter.php
  src/DataObject/Data/Adapter/LinkAdapter.php
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
  src/DataObject/Data/Adapter/ManyToManyObjectRelationAdapter.php
  src/DataObject/Data/Adapter/ManyToManyRelationAdapter.php
  src/DataObject/Data/Adapter/ManyToOneRelationAdapter.php
  src/DataObject/Data/Adapter/MultiSelectAdapter.php
  src/DataObject/Data/Adapter/NumericAdapter.php
  src/DataObject/Data/Adapter/NumericRangeAdapter.php
  src/DataObject/Data/Adapter/ObjectBricksAdapter.php
  src/DataObject/Data/Adapter/QuantityValueAdapter.php
  src/DataObject/Data/Adapter/QuantityValueRangeAdapter.php
  src/DataObject/Data/Adapter/ReverseObjectRelationAdapter.php
  src/DataObject/Data/Adapter/RgbaColorAdapter.php
  src/DataObject/Data/Adapter/SelectAdapter.php
  src/DataObject/Data/Adapter/SliderAdapter.php
  src/DataObject/Data/Adapter/StringAdapter.php
  src/DataObject/Data/Adapter/StructuredTableAdapter.php
  src/DataObject/Data/Adapter/TableAdapter.php
  src/DataObject/Data/Adapter/UrlSlugAdapter.php
  src/DataObject/Data/Adapter/VideoAdapter.php
  src/DataObject/Data/Model/ClassData.php
  src/DataObject/Data/Model/ConsentData.php
  src/DataObject/Data/Model/FieldContextData.php
  src/DataObject/Data/Model/RelationData.php
  src/DataObject/Data/SetterDataInterface.php
  src/DataObject/Service/DataService.php
  src/DataObject/Service/DataServiceInterface.php
Labels: Improvement

#595 [Documents] Get Available Sites endpoint
  config/documents.yaml
  src/Asset/Controller/Video/ImageThumbnailStreamController.php
  src/Document/Attribute/Response/AvailableSitesJson.php
  src/Document/Controller/AvailableSitesController.php
  src/Document/Event/PreResponse/SiteEvent.php
  src/Document/Hydrator/SiteHydrator.php
  src/Document/Hydrator/SiteHydratorInterface.php
  src/Document/MappedParameter/ExcludeMainSiteParameter.php
  src/Document/OpenApi/Attribute/Parameter/Query/ExcludeMainSiteParameter.php
  src/Document/Repository/SiteRepository.php
  src/Document/Repository/SiteRepositoryInterface.php
  src/Document/Schema/Site.php
  src/Document/Service/SiteService.php
  src/Document/Service/SiteServiceInterface.php
  src/OpenApi/Config/Tags.php
  translations/studio_api_docs.en.yaml
Labels: New Feature
