Repository pimcore/studio-backend-bundle, pull requests merged in 2024-10, with the labels that each got.

#448 [Security] Reenable roave/security-addvisories
  composer.json
Labels: Security

#456 [Bug]: Fix duplicated schema name.
  src/Asset/Schema/Type/Document.php
  src/Document/Schema/Document.php
Labels: Bug

#455 [Task] Switch exception type
  src/Asset/Controller/Download/CreateZipController.php
  src/Asset/Service/ExecutionEngine/ZipService.php
  src/Asset/Service/ExecutionEngine/ZipServiceInterface.php
  src/Exception/Api/MaxFileSizeExceededException.php
Labels: Task

#457 [Grid] [DataObject] Show system grid data
  src/DataIndex/AssetSearchResult.php
  src/DataIndex/DataObjectSearchResult.php
  src/DataIndex/Grid/GridSearch.php
  src/DataIndex/Grid/GridSearchInterface.php
  src/DataIndex/SearchResult/SearchResultItemInterface.php
  src/DataIndex/SearchResult/SearchResultPaginationInterface.php
  src/DataObject/Controller/Grid/GetController.php
  src/DataObject/Schema/DataObject.php
  src/Grid/Service/GridService.php
  src/Grid/Service/GridServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Task

#450 [Task] Update controller responses to jobrunid instead of id
  src/Asset/Controller/CloneController.php
  src/Asset/Controller/PatchController.php
  src/Asset/Controller/Upload/ZipController.php
Labels: Task

#461 Enable syncronus update for GDI when patching
  src/Patcher/Service/PatchService.php
Labels: Task

#467 [Task] Narrow down return type
  src/Asset/Service/AssetService.php
  src/DataIndex/Adapter/AssetSearchAdapter.php
  src/DataIndex/Adapter/AssetSearchAdapterInterface.php
  src/DataIndex/AssetSearchService.php
  src/DataIndex/AssetSearchServiceInterface.php
  src/DataIndex/Grid/GridSearch.php
  src/DataIndex/Provider/AssetQueryProvider.php
  src/DataIndex/Provider/AssetQueryProviderInterface.php
  src/DataIndex/Query/AssetQuery.php
  src/DataIndex/Query/AssetQueryInterface.php
  tests/Unit/Service/Factory/QueryFactoryTest.php
Labels: Task

#471 [Task] If empty list, add default metadata
  src/Asset/Service/Data/CustomMetadataService.php
  src/Asset/Service/Data/CustomMetadataServiceInterface.php
Labels: Task, Pimcore:ToDo

#475 [Grid] [Asset] Predefined Metadata should be localizable.
  src/Grid/Column/Collector/Asset/MetadataCollector.php
Labels: Bug

#474 Use CustomMetadataServiceInterface for Default Metadate.
  src/Grid/Column/Collector/Asset/MetadataCollector.php
Labels: Improvement

#478 [Bug] Async processes do not have user in session
  src/Element/ExecutionEngine/AutomationAction/Messenger/Handler/PatchHandler.php
  src/Patcher/Service/PatchService.php
  src/Patcher/Service/PatchServiceInterface.php
Labels: Pimcore:ToDo, Bug

#479 [Grid] [Asset] Save Configuration shared User and role can be empty.
  src/Asset/MappedParameter/Grid/SaveConfigurationParameter.php
Labels: Bug

#480 [Grid] [Dataobject] Add Folder ID to custom layout getter.
  src/Grid/Column/Collector/DataObject/FieldDefinitionCollector.php
Labels: Bug

#488 [Grid] [DataObject] List available columns for object Bricks
  config/grid.yaml
  src/Grid/Column/Collector/DataObject/FieldDefinitionCollector.php
  src/Grid/Column/Collector/DataObject/ObjectBrickCollector.php
  src/Grid/Column/Collector/DataObject/SystemFieldCollector.php
  src/Grid/Service/ClassDefinitionService.php
  src/Grid/Service/ClassDefinitionServiceInterface.php
  src/Grid/Service/ColumnConfigurationService.php
  src/Grid/Service/ColumnConfigurationServiceInterface.php
Labels: Improvement

#490 [Grid] [Asset] Load Favorite configuration as default when set
  src/Grid/Service/ConfigurationService.php
  src/Grid/Service/FavoriteService.php
  src/Grid/Service/FavoriteServiceInterface.php
Labels: Improvement

#491 [Task] Set pattern dynamically, add url_prefix check
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/Exception/InvalidUrlPrefixException.php
Labels: Task, Pimcore:ToDo

#493 [Grid] [Asset] Save Configuration should return configuration schema
  src/Asset/Controller/Grid/Configuration/SaveConfigurationController.php
  src/Asset/Service/Grid/SaveConfigurationService.php
  src/Asset/Service/Grid/SaveConfigurationServiceInterface.php
Labels: Improvement

#495 [Grid] [Asset] List configuration use collection to match with schema
  src/Grid/Service/ConfigurationService.php
  src/Grid/Service/ConfigurationServiceInterface.php
Labels: Bug

#497 [Grid] [Asset] Update schema for Detailed Configuration
  src/Grid/Schema/DetailedConfiguration.php
Labels: Improvement

#499 [Task] Update subscribers and docs
  config/event_subscribers.yaml
  doc/00_Installation.md
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/EventSubscriber/ApiExceptionSubscriber.php
  src/EventSubscriber/CorsSubscriber.php
  src/Util/Trait/StudioBackendPathTrait.php
Labels: Task, Pimcore:ToDo

#500 [Grid] [Asset] Add ID to DetailedConfiguration
  src/Grid/Hydrator/DetailedConfigurationHydrator.php
  src/Grid/Schema/DetailedConfiguration.php
Labels: Improvement

#451 [Feat] Add DataObject adapters
  config/data_objects.yaml
  config/pimcore/config.yaml
  config/updater.yaml
  src/DataObject/Attribute/Request/UpdateDataObjectRequestBody.php
  src/DataObject/Data/Adapter/AdvancedManyToManyObjectRelationAdapter.php
  src/DataObject/Data/Adapter/AdvancedManyToManyRelationAdapter.php
  src/DataObject/Data/Adapter/BlockAdapter.php
  src/DataObject/Data/Adapter/BooleanAdapter.php
  src/DataObject/Data/Adapter/CalculatedValueAdapter.php
  src/DataObject/Data/Adapter/CheckboxAdapter.php
  src/DataObject/Data/Adapter/ClassificationStoreAdapter.php
  src/DataObject/Data/Adapter/ConsentAdapter.php
  src/DataObject/Data/Adapter/DateAdapter.php
  src/DataObject/Data/Adapter/DateRangeAdapter.php
  src/DataObject/Data/Adapter/EncryptedFieldAdapter.php
  src/DataObject/Data/Adapter/ExternalImageAdapter.php
  src/DataObject/Data/Adapter/FieldCollectionsAdapter.php
  src/DataObject/Data/Adapter/GeoBoundsAdapter.php
  src/DataObject/Data/Adapter/GeoPointAdapter.php
  src/DataObject/Data/Adapter/GeoPointsAdapter.php
  src/DataObject/Data/Adapter/HotspotImageAdapter.php
  src/DataObject/Data/Adapter/ImageAdapter.php
  src/DataObject/Data/Adapter/ImageGalleryAdapter.php
  src/DataObject/Data/Adapter/InputQuantityValueAdapter.php
  src/DataObject/Data/Adapter/LinkAdapter.php
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
  src/DataObject/Data/Adapter/ManyToManyObjectRelationAdapter.php
  src/DataObject/Data/Adapter/ManyToManyRelationAdapter.php
  src/DataObject/Data/Adapter/ManyToOneRelationAdapter.php
  src/DataObject/Data/Adapter/MultiSelectAdapter.php
  src/DataObject/Data/Adapter/NumericAdapter.php
  src/DataObject/Data/Adapter/NumericRangeAdapter.php
  src/DataObject/Data/Adapter/ObjectBricksAdapter.php
  src/DataObject/Data/Adapter/QuantityValueAdapter.php
  src/DataObject/Data/Adapter/QuantityValueRangeAdapter.php
  src/DataObject/Data/Adapter/ReverseObjectRelationAdapter.php
  src/DataObject/Data/Adapter/RgbaColorAdapter.php
  src/DataObject/Data/Adapter/SelectAdapter.php
  src/DataObject/Data/Adapter/SliderAdapter.php
  src/DataObject/Data/Adapter/StringAdapter.php
  src/DataObject/Data/Adapter/StructuredTableAdapter.php
  src/DataObject/Data/Adapter/TableAdapter.php
  src/DataObject/Data/Adapter/UrlSlugAdapter.php
  src/DataObject/Data/Adapter/VideoAdapter.php
  src/DataObject/Data/FieldContextData.php
  src/DataObject/Data/SetterDataInterface.php
  src/DataObject/Service/DataAdapterLoaderInterface.php
  src/DataObject/Service/DataAdapterService.php
  src/DataObject/Service/DataAdapterServiceInterface.php
  src/DataObject/Service/Loader/TaggedIteratorDataAdapter.php
  src/DataObject/Util/Trait/DefaultSetterValueTrait.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/OpenApi/Attribute/Property/UpdateObjectProperty.php
  src/Updater/Service/UpdateService.php
  src/Util/Constant/DataObject/ContainerTypes.php
  src/Util/Constant/ElementPermissions.php
Labels: New Feature

#502 [Workflow] Update workflows update and response schema
  src/Workflow/Schema/AllowedTransition.php
  src/Workflow/Schema/SubmitAction.php
Labels: Improvement

#506 Update 00_Installation.md
  doc/00_Installation.md
Labels: Improvement

#505 [Task] Rename and move Csv enums
  src/Asset/Attribute/Request/CsvExportAssetRequestBody.php
  src/Asset/Attribute/Request/CsvExportFolderRequestBody.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvAssetDataCollectionHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvCreationHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvFolderDataCollectionHandler.php
  src/Asset/Service/ExecutionEngine/CsvService.php
  src/Asset/Util/Trait/CsvConfigValidationTrait.php
  src/Element/ExecutionEngine/AutomationAction/Messenger/Handler/PatchFolderHandler.php
  src/ExecutionEngine/Util/StepConfig.php
Labels: Task

#511 [Elements] Add option for Patcher and Updater to unlock & propagate elements
  src/Patcher/Adapter/LockAdapter.php
  src/Updater/Adapter/LockedAdapter.php
Labels: Improvement

#512 [Grid] [Asset] Delete Endpoint to delete a grid configuration.
  src/Asset/Controller/Grid/Configuration/DeleteConfigurationController.php
  src/Grid/Repository/ConfigurationRepository.php
  src/Grid/Repository/ConfigurationRepositoryInterface.php
  src/Grid/Service/ConfigurationService.php
  src/Grid/Service/ConfigurationServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#514 [Bug] Fix phpstorm not updating all namespaces
  src/Asset/Attribute/Request/CsvExportAssetRequestBody.php
  src/Asset/Attribute/Request/CsvExportFolderRequestBody.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvAssetDataCollectionHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvCreationHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvFolderDataCollectionHandler.php
  src/Asset/Service/ExecutionEngine/CsvService.php
  src/Asset/Util/Trait/CsvConfigValidationTrait.php
  src/Element/ExecutionEngine/AutomationAction/Messenger/Handler/PatchFolderHandler.php
  src/ExecutionEngine/Util/StepConfig.php
Labels: Bug

#510 Enable syncronus processing for creating a folder
  src/Element/Service/ElementFolderService.php
Labels: Improvement

#516 [Task] [GridSearch] Refactor not use AssetService or DataObjectService
  src/DataIndex/Grid/GridSearch.php
Labels: Improvement

#518 [Assets][Image] Add endpoint to return image preview based on studio config
  src/Asset/Controller/Image/PreviewStreamController.php
  src/Asset/Service/BinaryService.php
  src/Asset/Service/BinaryServiceInterface.php
  src/Asset/Service/ThumbnailService.php
  src/Asset/Service/ThumbnailServiceInterface.php
  src/Util/Constant/Asset/MimeTypes.php
  src/Util/Constant/Thumbnails.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#519 [Grid] [Resolver] Asset Documnet and DataObject Resolver for Metadata should not throw a NotFoundException
  src/DataIndex/Adapter/DocumentSearchAdapter.php
  src/Grid/Column/Resolver/Metadata/AssetResolver.php
  src/Grid/Column/Resolver/Metadata/DataObjectResolver.php
  src/Grid/Column/Resolver/Metadata/DocumentResolver.php
Labels: Bug

#492 [Task] Add zip creation based on folder ids
  src/Asset/Attribute/Request/ZipExportFolderRequestBody.php
  src/Asset/Controller/Export/ZipAssetController.php
  src/Asset/Controller/Export/ZipFolderController.php
  src/Asset/MappedParameter/ExportAssetFileParameter.php
  src/Asset/MappedParameter/ExportFolderFileParameter.php
  src/Asset/Service/ExecutionEngine/ZipService.php
  src/Asset/Service/ExecutionEngine/ZipServiceInterface.php
  src/OpenApi/Attribute/Content/ScalarItemsJson.php
  translations/studio_api_docs.en.yaml
Labels: Task, Pimcore:ToDo

#520 [DataObject]: Add endpoint to list data object layouts
  config/data_objects.yaml
  src/DataIndex/Hydrator/HydratorService.php
  src/DataObject/Controller/LayoutController.php
  src/DataObject/Event/PreResponse/LayoutEvent.php
  src/DataObject/Schema/Layout.php
  src/DataObject/Service/LayoutService.php
  src/DataObject/Service/LayoutServiceInterface.php
  src/Icon/Service/IconService.php
  src/Icon/Service/IconServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature
