Repository pimcore/studio-backend-bundle, pull requests merged in 2024-07, with the labels that each got.

#204 [Task] Fix php version
  composer.json
Labels: Task

#211 [Task] Collapse tags at start
  public/js/swagger-ui/swagger-initializer.js
Labels: Task

#209 [Asset versions] Check if asset version download endpoint should deliver thumbnail or original asset
  src/Version/Controller/Asset/PdfStreamController.php
  src/Version/Service/VersionBinaryService.php
  src/Version/Service/VersionBinaryServiceInterface.php
  src/Workflow/Schema/WorkflowStatus.php
  src/Workflow/Service/WorkflowDetailsService.php
Labels: Improvement

#206 [Feature] Grid Functionality
  config/grid.yaml
  src/Asset/Controller/Grid/Configuration/GetController.php
  src/Asset/Controller/Grid/GetController.php
  src/DataIndex/Grid/GridSearch.php
  src/DataIndex/Grid/GridSearchInterface.php
  src/DependencyInjection/CompilerPass/GridColumnDefinitionPass.php
  src/DependencyInjection/CompilerPass/GridColumnResolverPass.php
  src/Grid/Attributes/Property/GridCollection.php
  src/Grid/Attributes/Request/GridRequestBody.php
  src/Grid/Column/ColumnDefinitionInterface.php
  src/Grid/Column/ColumnResolverInterface.php
  src/Grid/Column/Definition/DatetimeDefinition.php
  src/Grid/Column/Definition/FileSizeDefinition.php
  src/Grid/Column/Definition/ImageDefinition.php
  src/Grid/Column/Definition/IntegerDefinition.php
  src/Grid/Column/Definition/StringDefinition.php
  src/Grid/Column/Resolver/DatetimeResolver.php
  src/Grid/Column/Resolver/FileSizeResolver.php
  src/Grid/Column/Resolver/ImageResolver.php
  src/Grid/Column/Resolver/IntegerResolver.php
  src/Grid/Column/Resolver/StringResolver.php
  src/Grid/Event/GridColumnDataEvent.php
  src/Grid/Event/GridColumnDefinitionEvent.php
  src/Grid/MappedParameter/GridParameter.php
  src/Grid/Mapper/ColumnMapper.php
  src/Grid/Mapper/ColumnMapperInterface.php
  src/Grid/Schema/Column.php
  src/Grid/Schema/ColumnData.php
  src/Grid/Schema/Configuration.php
  src/Grid/Service/ColumnDefinitionLoaderInterface.php
  src/Grid/Service/ColumnResolverLoaderInterface.php
  src/Grid/Service/GridService.php
  src/Grid/Service/GridServiceInterface.php
  src/Grid/Service/Loader/TaggedIteratorColumnDefinitionLoader.php
  src/Grid/Service/Loader/TaggedIteratorColumnResolverLoader.php
  src/Grid/Service/SystemColumnService.php
  src/Grid/Service/SystemColumnServiceInterface.php
  src/Grid/Util/Trait/ColumnDataTrait.php
  src/Grid/Util/Trait/SimpleGetterTrait.php
  src/OpenApi/Attributes/Property/SingleInteger.php
  src/OpenApi/Config/Tags.php
  src/PimcoreStudioBackendBundle.php
Labels: New Feature

#213 [Asset Upload] Single Upload
  config/assets.yaml
  src/Asset/Attributes/Request/AddAssetRequestBody.php
  src/Asset/Controller/Upload/AddController.php
  src/Asset/Service/UploadService.php
  src/Asset/Service/UploadServiceInterface.php
Labels: New Feature

#224 [Task] Make note data types narrower
  src/Note/Schema/Note.php
Labels: Task

#225 [Task] Improve cors listener and performance bottleneck
  src/EventSubscriber/CorsSubscriber.php
Labels: Task

#235 [Task] Adding userid to finished event for SSE
  src/Asset/EventSubscriber/CloneSubscriber.php
  src/Asset/EventSubscriber/DeletionSubscriber.php
  src/Asset/EventSubscriber/UploadSubscriber.php
  src/Asset/EventSubscriber/ZipUploadSubscriber.php
  src/ExecutionEngine/EventSubscriber/FailureSubscriber.php
  src/ExecutionEngine/Service/EventSubscriberService.php
  src/ExecutionEngine/Service/EventSubscriberServiceInterface.php
  src/Mercure/Schema/ExecutionEngine/Finished.php
Labels: Task

#236 [Task] Introduce lifetime and hubservice
  config/mercure.yaml
  doc/02_Mercure_Setup.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/Mercure/Controller/JwtController.php
  src/Mercure/Service/HubService.php
  src/Mercure/Service/HubServiceInterface.php
  src/Mercure/Util/Constants/Mercure.php
Labels: Task

#237 Fix getAssetExists route name
  src/Asset/Controller/Upload/InfoController.php
Labels: Task

#240 [Task] Update installation guide, firewall needs to be configured before installation
  doc/01_Installation.md
Labels: Task

#243 [Task] Fix name
  src/Asset/Controller/DownloadCsvController.php
Labels: Task

#251 [Bug] Fix storage path
  src/Asset/Service/ExecutionEngine/ZipService.php
Labels: Bug

#242 Email - Blocklist
  config/emails.yaml
  src/Email/Attributes/Request/BlocklistRequestBody.php
  src/Email/Attributes/Response/Property/BlocklistCollection.php
  src/Email/Controller/Blocklist/AddController.php
  src/Email/Controller/Blocklist/CollectionController.php
  src/Email/Controller/Blocklist/DeleteController.php
  src/Email/Event/PreResponse/BlocklistEntryEvent.php
  src/Email/Repository/BlocklistRepository.php
  src/Email/Repository/BlocklistRepositoryInterface.php
  src/Email/Schema/BlocklistEntry.php
  src/Email/Schema/BlocklistEntryRequest.php
  src/Email/Service/BlocklistService.php
  src/Email/Service/BlocklistServiceInterface.php
  src/OpenApi/Config/Tags.php
  src/Util/Constants/UserPermissions.php
Labels: New Feature

#249 Email - Send Testmail
  config/emails.yaml
  src/Email/Attributes/Request/TestEmailRequestBody.php
  src/Email/Controller/TestEmailController.php
  src/Email/Schema/EmailDocumentParameters.php
  src/Email/Schema/TestEmailRequest.php
  src/Email/Service/EmailService.php
  src/Email/Service/EmailServiceInterface.php
  src/Email/Util/Constants/TestEmailContentType.php
Labels: New Feature

#268 Added path prefix `assign` to routes in `AssignController`
  src/Tag/Controller/Element/AssignController.php
Labels: Bug

#271 Version preview exception
  src/Version/Hydrator/CustomMetadataVersionHydrator.php
Labels: Improvement

#274 [Task]: Downloads should be able to be aborted & deleted
  config/execution_engine.yaml
  src/Asset/Controller/Download/CreateCsvController.php
  src/Asset/Controller/Download/CreateZipController.php
  src/Asset/Controller/Download/DeleteCsvController.php
  src/Asset/Controller/Download/DeleteZipController.php
  src/Asset/Controller/Download/DownloadCsvController.php
  src/Asset/Controller/Download/DownloadZipController.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/AssetCloneHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/AssetDeleteHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/AssetUploadHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvCreationHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvDataCollectionHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/ZipDownloadHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/ZipUploadHandler.php
  src/Asset/Service/DownloadService.php
  src/Asset/Service/DownloadServiceInterface.php
  src/ExecutionEngine/AutomationAction/AbstractHandler.php
  src/ExecutionEngine/Controller/AbortController.php
  src/ExecutionEngine/Service/ExecutionEngineService.php
  src/ExecutionEngine/Service/ExecutionEngineServiceInterface.php
  src/OpenApi/Config/Tags.php
Labels: Improvement

#275 [Notes&Event] User should be saved when creating a new note
  src/Note/Controller/Element/CreateController.php
  src/Note/Repository/NoteRepository.php
  src/Note/Repository/NoteRepositoryInterface.php
  src/Note/Service/NoteService.php
  src/Note/Service/NoteServiceInterface.php
Labels: Task

#278 [Execution Engine] Adapt progress calculation
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/AssetCloneHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/AssetDeleteHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/AssetUploadHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvCreationHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/CsvDataCollectionHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/ZipDownloadHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/ZipUploadHandler.php
  src/Element/ExecutionEngine/AutomationAction/Messenger/Handler/PatchHandler.php
  src/ExecutionEngine/EventSubscriber/FailureSubscriber.php
  src/ExecutionEngine/Util/Trait/HandlerProgressTrait.php
  src/Mercure/Schema/ExecutionEngine/Progress.php
  src/Util/Traits/HandlerProgressTrait.php
Labels: Improvement

#280 [Bug] Fix Type check.
  src/Asset/Service/DocumentService.php
  src/Asset/Service/DownloadService.php
  src/Asset/Service/ExecutionEngine/CloneService.php
  src/Asset/Service/ExecutionEngine/ZipService.php
  src/Asset/Service/UploadService.php
  src/DataIndex/Adapter/AssetSearchAdapter.php
  src/DataIndex/Adapter/DataObjectSearchAdapter.php
  src/DataIndex/Filter/Asset/MetaData/IsAssetMetaDataTrait.php
  src/DependencyInjection/CompilerPass/MercureTopicsProviderPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/Element/Service/ElementDeleteService.php
  src/Element/Service/ElementFolderService.php
  src/Element/Service/StorageService.php
  src/Email/Repository/BlocklistRepository.php
  src/Email/Service/EmailService.php
  src/Exception/Api/ConsoleDependencyMissingException.php
  src/Exception/Api/ElementDeletingFailedException.php
  src/Exception/Api/ElementDeletionFailedException.php
  src/Exception/Api/ElementProcessingNotCompletedException.php
  src/Exception/Api/ElementPublishingFailedException.php
  src/Exception/Api/ElementSavingFailedException.php
  src/Exception/Api/ElementStreamResourceNotFoundException.php
  src/Exception/Api/InvalidActionTypeException.php
  src/Exception/Api/InvalidAssetFormatTypeException.php
  src/Exception/Api/InvalidElementTypeException.php
  src/Exception/Api/InvalidFilterException.php
  src/Exception/Api/InvalidLocaleException.php
  src/Exception/Api/InvalidParentIdException.php
  src/Exception/Api/InvalidThumbnailConfigurationException.php
  src/Exception/Api/InvalidThumbnailException.php
  src/Exception/Api/MaxFileSizeExceededException.php
  src/Exception/Api/NotCompletedException.php
  src/Exception/Api/NotFoundException.php
  src/Exception/Api/NotWriteableException.php
  src/Exception/Api/SendMailException.php
  src/Exception/Api/ThumbnailResizingFailedException.php
  src/Exception/Api/WorkflowActionNotAllowedException.php
  src/Exception/Api/WorkflowActionNotFoundException.php
  src/Exception/Api/WorkflowActionSubmissionException.php
  src/ExecutionEngine/Service/ExecutionEngineService.php
  src/Mercure/Service/PublishService.php
  src/OpenApi/Attributes/Response/DefaultResponses.php
  src/Role/Repository/RoleRepository.php
  src/Role/Service/FolderService.php
  src/Role/Service/RoleService.php
  src/Security/Service/SecurityService.php
  src/Security/Voter/UserPermissionVoter.php
  src/User/Repository/UserRepository.php
  src/User/Service/MailService.php
  src/User/Service/UserFolderService.php
  src/User/Service/UserService.php
  src/User/Service/UserUpdateService.php
  src/Util/Traits/MustImplementInterfaceTrait.php
  src/Util/Traits/PublicTranslationTrait.php
  src/Util/Traits/StreamedResponseTrait.php
Labels: Bug

#288 #286 [Grid] Fix Schema.
  src/Grid/Schema/ColumnConfiguration.php
  src/Grid/Schema/Filter.php
Labels: Bug

#287 #262 [Grid] Add sorting filter
  config/data_index_filters.yaml
  src/DataIndex/Filter/Asset/SortFilter.php
  src/DataIndex/Query/AssetQuery.php
  src/Grid/MappedParameter/FilterParameter.php
  src/Grid/Schema/Filter.php
  src/MappedParameter/Filter/SortFilter.php
  src/MappedParameter/Filter/SortFilterParameterInterface.php
Labels: Improvement
