Repository pimcore/studio-backend-bundle, pull requests merged in 2024-09, with the labels that each got.

#405 [Data Object] Add index sorting for the tree endpoint
  config/patcher.yaml
  config/updater.yaml
  src/DataIndex/Hydrator/DataObject/FolderHydrator.php
  src/DataIndex/Hydrator/DataObjectHydrator.php
  src/DataIndex/Query/DataObjectQuery.php
  src/DataObject/Attribute/Request/PatchDataObjectRequestBody.php
  src/DataObject/Attribute/Request/UpdateDataObjectRequestBody.php
  src/DataObject/Controller/TreeController.php
  src/DataObject/Schema/DataObject.php
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataObjectServiceInterface.php
  src/Patcher/Adapter/ChildrenSortByAdapter.php
  src/Patcher/Adapter/ChildrenSortOrderAdapter.php
  src/Patcher/Adapter/IndexAdapter.php
  src/Updater/Adapter/ChildrenSortByAdapter.php
  src/Updater/Adapter/ChildrenSortOrderAdapter.php
  src/Updater/Adapter/IndexAdapter.php
  src/Util/Constant/UserPermissions.php
Labels: Improvement

#401 [Testing] Set up local testing environment.
  .gitignore
  doc/06_Api_Testing.md
  tests/Api/boot-test-env.sh
  tests/Api/bundles.php
  tests/Api/docker-compose.yaml
  tests/Api/opensearch-config.yaml
  tests/Api/studio-config.yaml
Labels: Task

#407 [Testing] Update testing config
  doc/06_Api_Testing.md
  tests/Api/boot-test-env.sh
  tests/Api/docker-compose.yaml
  tests/Api/opensearch-config.yaml
Labels: Task

#406 Problem when requesting 2 version preview image streams from the same asset ID in parallel
  src/Version/Service/VersionBinaryService.php
Labels: Task

#409 [Testing] Add GitHub action for API Test
  .github/workflows/api-test.yaml
Labels: Task

#411 Add Integration Test Issue Template.
  .github/ISSUE_TEMPLATE/Integration-Test.yaml
Labels: Task

#414 [Integration Test] Move Clone user test into User Management.
  tests/Api/postman/collections/Integration Test.json
Labels: Testing

#417 Disable roave/security due to a twig security issue
  composer.json
Labels: Task

#416 [Improvement] Created new schedule for update if no id is sent
  src/Schedule/Repository/ScheduleRepository.php
  src/Schedule/Schema/UpdateSchedule.php
Labels: Improvement

#419 [Testing] Add postman docs
  doc/06_Api_Testing.md
Labels: Testing

#420 [User Management] List all available users
  doc/05_Additional_Custom_Attributes.md
  src/User/Controller/GetUsersController.php
  src/User/Event/SimpleUserEvent.php
  src/User/Repository/UserRepository.php
  src/User/Repository/UserRepositoryInterface.php
  src/User/Schema/SimpleUser.php
  src/User/Service/UserService.php
  src/User/Service/UserServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Task

#421 [Role Management] List all available Roles
  src/Role/Controller/GetRolesController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#424 [Grid] Add Owner and Modification Date
  src/Grid/Hydrator/DetailedConfigurationHydrator.php
  src/Grid/Schema/DetailedConfiguration.php
Labels: Task

#430 Introduce two new interfaces for DataIndex Query
  docker-compose.yml
  src/DataIndex/Filter/Asset/IsAssetFilterTrait.php
  src/DataIndex/Filter/Asset/Metadata/AssetFilter.php
  src/DataIndex/Filter/Asset/Metadata/CheckboxFilter.php
  src/DataIndex/Filter/Asset/Metadata/DateFilter.php
  src/DataIndex/Filter/Asset/Metadata/DocumentFilter.php
  src/DataIndex/Filter/Asset/Metadata/InputFilter.php
  src/DataIndex/Filter/Asset/Metadata/ObjectFilter.php
  src/DataIndex/Filter/Asset/Metadata/SelectFilter.php
  src/DataIndex/Filter/Asset/Metadata/TextAreaFilter.php
  src/DataIndex/Filter/Asset/SortFilter.php
  src/DataIndex/Filter/Asset/System/DatetimeFilter.php
  src/DataIndex/Filter/Asset/System/StringFilter.php
  src/DataIndex/Filter/DataObject/ClassNameFilter.php
  src/DataIndex/Query/AssetQuery.php
  src/DataIndex/Query/AssetQueryInterface.php
  src/DataIndex/Query/DataObjectQuery.php
  src/DataIndex/Query/DataObjectQueryInterface.php
  tests/Unit/DataIndex/Filter/Asset/IsAssetFilterTraitTest.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/AssetFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/CheckboxFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/ColumnFilterMockTrait.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/DateFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/DocumentFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/InputFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/ObjectFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/SelectFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/TextAreaFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/SortFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/System/DatetimeFilterTest.php
  tests/Unit/DataIndex/Filter/Asset/System/StringFilterTest.php
Labels: Improvement

#439 [Grid] [DataObject] List available system columns
  config/grid.yaml
  src/DataObject/Controller/Grid/GetAvailableColumnsController.php
  src/Grid/Column/Collector/Asset/MetadataCollector.php
  src/Grid/Column/Collector/Asset/SystemFieldCollector.php
  src/Grid/Column/Collector/DataObject/SystemFieldCollector.php
  src/Grid/Mapper/ColumnMapper.php
  src/Grid/Service/ColumnConfigurationService.php
  src/Grid/Service/ColumnConfigurationServiceInterface.php
  src/Grid/Service/SystemColumnService.php
  src/Grid/Service/SystemColumnServiceInterface.php
  src/OpenApi/Attribute/Parameter/Path/StringParameter.php
  src/OpenApi/Config/Tags.php
  tests/Unit/Grid/Mapper/ColumnMapperTest.php
  tests/Unit/Grid/Service/SystemColumnServiceTest.php
  translations/studio_api_docs.en.yaml
Labels: Task

#442 [Grid] Fix duplicated system collector name.
  src/Grid/Column/Collector/Asset/SystemFieldCollector.php
  src/Grid/Column/Collector/DataObject/SystemFieldCollector.php
Labels: Bug

#445 [Tags][Notes] Data objects API problem
  src/Note/MappedParameter/NoteElementParameters.php
  src/Tag/Controller/Element/BatchAssignController.php
  src/Tag/Controller/Element/BatchReplaceController.php
  src/Tag/MappedParameter/ElementParameters.php
Labels: Task

#446 [Task] Use trait to avoid code duplication
  src/Note/MappedParameter/NoteElementParameters.php
  src/Tag/MappedParameter/ElementParameters.php
  src/Util/Trait/ValidateElementTypeTrait.php
Labels: Task
