Repository pimcore/studio-backend-bundle, pull requests merged in 2024-12, with the labels that each got.

#604 [Task] Language is nullable
  src/Version/Schema/CustomMetadataVersion.php
Labels: Task

#609 [Data Object Editor] Field-Collections with block and localized fields not working
  composer.json
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
Labels: Bug

#606 [Task] Add exportable flag to grid columns config
  src/DataObject/Controller/Grid/GetAvailableColumnsController.php
  src/Grid/Column/Collector/Asset/MetadataCollector.php
  src/Grid/Column/Collector/Asset/SystemFieldCollector.php
  src/Grid/Column/Collector/DataObject/SystemFieldCollector.php
  src/Grid/Schema/ColumnConfiguration.php
  src/Grid/Service/ColumnConfigurationService.php
  src/Grid/Service/GridService.php
Labels: Task, Pimcore:ToDo

#615 [Task] Add roave/security-advisories
  composer.json
Labels: Task

#612 [Task][Asset] Add thumbnail clear
  src/Asset/Controller/Image/ThumbnailImageClearController.php
  src/Asset/Service/AssetService.php
  src/Asset/Service/AssetServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Task, Pimcore:ToDo

#617 [Task] Update ACL
  doc/00_Installation.md
Labels: Task

#619 [Data Object Editor] Quantity value endpoints tag handling
  config/class.yaml
  config/units.yaml
  src/OpenApi/Attribute/Parameter/Query/TextFieldParameter.php
  src/OpenApi/Config/Tags.php
  src/Unit/Attribute/Parameter/Query/ValueParameter.php
  src/Unit/Attribute/Response/ConvertedValueJson.php
  src/Unit/Attribute/Response/QuantityValueUnitsJson.php
  src/Unit/Controller/QuantityValue/ConvertAllController.php
  src/Unit/Controller/QuantityValue/ConvertController.php
  src/Unit/Controller/QuantityValue/UnitListController.php
  src/Unit/Event/PreResponse/QuantityValueConversionEvent.php
  src/Unit/Event/PreResponse/QuantityValueUnitEvent.php
  src/Unit/MappedParameter/ConvertAllUnitsParameter.php
  src/Unit/MappedParameter/ConvertUnitParameter.php
  src/Unit/Repository/QuantityValueRepository.php
  src/Unit/Repository/QuantityValueRepositoryInterface.php
  src/Unit/Schema/ConvertParameters.php
  src/Unit/Schema/ConvertedQuantityValue.php
  src/Unit/Schema/ConvertedQuantityValues.php
  src/Unit/Schema/QuantityValueUnit.php
  src/Unit/Service/QuantityValueService.php
  src/Unit/Service/QuantityValueServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#621 [Data Object Tree] Change className property to string instead of enum
  src/DataObject/Attribute/Parameter/Query/ClassNameParameter.php
  src/DataObject/Controller/TreeController.php
Labels: Task

#614 [Feature][Asset] Stream image thumbnail action
  src/Asset/Controller/Image/CustomStreamController.php
  src/Asset/MappedParameter/ImageDownloadConfigParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/ContainParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/CoverParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/ForceResizeParameter.php
  src/Asset/Service/BinaryService.php
  src/Asset/Service/BinaryServiceInterface.php
  src/Asset/Service/ThumbnailService.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#623 [Workflows] Schema
  src/Workflow/Schema/SubmitAction.php
  src/Workflow/Service/WorkflowDetailsService.php
  tests/Unit/Workflow/Schema/SubmitActionTest.php
Labels: Task

#625 [Settings] Add map settings
  src/Setting/Provider/ConfigSettingsProvider.php
Labels: Improvement

#629 [Improvement] Added default value for quality
  src/Asset/Controller/Image/CustomStreamController.php
Labels: Improvement

#627 [Task] Missing http responses
  src/Asset/Controller/GetController.php
  src/Asset/Controller/Grid/Configuration/GetAvailableColumnsController.php
  src/Asset/Controller/Grid/Configuration/GetConfigurationController.php
  src/Asset/Controller/Grid/Configuration/ListSavedConfigurationsController.php
  src/Asset/Controller/Image/ThumbnailDownloadController.php
  src/Asset/Controller/TreeController.php
  src/Role/Controller/CloneController.php
  src/Role/Controller/CreateFolderController.php
  src/Role/Controller/CreateRoleController.php
  src/Role/Controller/DeleteFolderController.php
  src/Role/Controller/DeleteRoleController.php
  src/Role/Controller/GetRoleController.php
  src/Role/Controller/RoleTreeController.php
  src/Role/Controller/UpdateRoleController.php
  src/User/Controller/CloneController.php
  src/User/Controller/CreateUserController.php
  src/User/Controller/CreateUserFolderController.php
  src/User/Controller/DeleteUserFolderController.php
  src/User/Controller/UpdateUserController.php
Labels: Task

#632 [Asset Replace] Return original file name not the new one
  src/Asset/Service/UploadService.php
Labels: Improvement

#636 [Asset Replace] Return new file name as response
  src/Asset/Controller/Upload/ReplaceController.php
  src/Asset/Service/UploadService.php
  src/Asset/Service/UploadServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#631 [Data Object Editor] Get Select Options Endpoint
  config/data_objects.yaml
  src/DataObject/Attribute/Request/SelectOptionRequestBody.php
  src/DataObject/Controller/SelectOptionsController.php
  src/DataObject/Event/PreResponse/DynamicSelectOptionEvent.php
  src/DataObject/Hydrator/SelectOptionHydrator.php
  src/DataObject/Hydrator/SelectOptionHydratorInterface.php
  src/DataObject/Legacy/ApplyChangesHelper.php
  src/DataObject/Legacy/ApplyChangesHelperInterface.php
  src/DataObject/MappedParameter/SelectOptionsParameter.php
  src/DataObject/Schema/SelectOption.php
  src/DataObject/Service/SelectOptionsService.php
  src/DataObject/Service/SelectOptionsServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#637 [Data Object] Add encrypted field normalizer
  src/DataObject/Data/Adapter/EncryptedFieldAdapter.php
Labels: Improvement

#641 [Image Editor] Add adapter to update data sent from asset editor
  config/assets.yaml
  src/Asset/Attribute/Request/UpdateAssetRequestBody.php
  src/Asset/Updater/Adapter/DataUriAdapter.php
Labels: Improvement

#643 [Asset] Stream image thumbnail action improvements
  src/Asset/Controller/Image/CustomStreamController.php
  src/Asset/MappedParameter/ImageDownloadConfigParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/MimeTypeParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/ResizeModeParameter.php
  src/Asset/Service/ThumbnailService.php
  src/Util/Constant/Asset/ResizeModes.php
Labels: Improvement

#646 [Task] Rename OpenSearch namespaces and classes
  config/data_index.yaml
  config/data_index_filters.yaml
  doc/10_Extending_Studio/03_Filters.md
  doc/10_Extending_Studio/04_Filters/01_OpenSearch_Filters.md
  doc/10_Extending_Studio/04_Filters/01_Search_Index_Filters.md
  doc/10_Extending_Studio/04_Filters/02_Listing_Filters.md
  doc/10_Extending_Studio/README.md
  src/Asset/Service/AssetService.php
  src/DataIndex/Filter/Asset/Metadata/DateFilter.php
  src/DataIndex/Filter/IdSearchFilter.php
  src/DataIndex/Filter/Loader/TaggedIteratorAdapter.php
  src/DataIndex/Grid/GridSearch.php
  src/DataIndex/SearchIndexFilter.php
  src/DataIndex/SearchIndexFilterInterface.php
  src/DataObject/Service/DataObjectService.php
  tests/Unit/DataIndex/Filter/Asset/Metadata/DateFilterTest.php
Labels: Task

#647 [Data Objects]: Extend Patcher to use field adapters for editable data
  src/Asset/Controller/PatchController.php
  src/Asset/Controller/PatchFolderController.php
  src/Asset/Controller/UpdateController.php
  src/DataObject/Attribute/Request/PatchDataObjectRequestBody.php
  src/DataObject/Controller/PatchController.php
  src/DataObject/Controller/UpdateController.php
  src/Patcher/Service/PatchService.php
  src/Updater/Service/UpdateService.php
  src/Updater/Service/UpdateServiceInterface.php
Labels: Improvement
