Repository pimcore/studio-backend-bundle, pull requests merged in 2024-06, with the labels that each got.

#83 Switch to path parameters for element
  src/Dependency/Controller/Element/CollectionController.php
  src/Dependency/Request/DependencyParameters.php
  src/Dependency/Service/DependencyService.php
  src/Dependency/Service/DependencyServiceInterface.php
  src/Property/Controller/CollectionController.php
  src/Property/MappedParameter/PropertiesParameters.php
  src/Property/Repository/PropertyRepository.php
  src/Property/Repository/PropertyRepositoryInterface.php
  src/Property/Request/UpdateElementProperties.php
  src/Property/Service/PropertyService.php
  src/Property/Service/PropertyServiceInterface.php
  src/Request/ElementParameters.php
  src/Version/Controller/Element/CleanupController.php
  src/Version/Controller/Element/CollectionController.php
  src/Version/Repository/VersionRepository.php
  src/Version/Repository/VersionRepositoryInterface.php
  src/Version/Request/VersionCleanupParameters.php
  src/Version/Request/VersionParameters.php
  src/Version/Service/VersionService.php
  src/Version/Service/VersionServiceInterface.php
Labels: Improvement

#84 Sort schemas alphabetically
  src/OpenApi/Service/OpenApiService.php
Labels: Improvement

#85 Rename Request Namespace to MappedParameter
  src/Asset/Controller/UpdateController.php
  src/Asset/MappedParameter/UpdateAssetParameter.php
  src/DataIndex/Filter/DataObject/ClassNameFilter.php
  src/DataIndex/Filter/ExcludeFolderFilter.php
  src/DataIndex/Filter/FilterInterface.php
  src/DataIndex/Filter/IdSearchFilter.php
  src/DataIndex/Filter/PageFilter.php
  src/DataIndex/Filter/PageSizeFilter.php
  src/DataIndex/Filter/ParentIdFilter.php
  src/DataIndex/Filter/PathFilter.php
  src/DataIndex/OpenSearchFilter.php
  src/DataIndex/OpenSearchFilterInterface.php
  src/DataIndex/Request/ElementParameters.php
  src/DataIndex/Request/ElementParametersInterface.php
  src/Dependency/Controller/Element/CollectionController.php
  src/Dependency/MappedParameter/DependencyParameters.php
  src/Dependency/Service/DependencyService.php
  src/Dependency/Service/DependencyServiceInterface.php
  src/MappedParameter/CollectionParameters.php
  src/MappedParameter/CollectionParametersInterface.php
  src/MappedParameter/ElementParameters.php
  src/Note/Controller/CollectionController.php
  src/Note/Controller/Element/CollectionController.php
  src/Note/Controller/Element/CreateController.php
  src/Note/MappedParameter/NoteElementParameters.php
  src/Note/MappedParameter/NoteParameters.php
  src/Note/Repository/NoteRepository.php
  src/Note/Repository/NoteRepositoryInterface.php
  src/Note/Service/FilterService.php
  src/Note/Service/FilterServiceInterface.php
  src/Note/Service/NoteService.php
  src/Note/Service/NoteServiceInterface.php
  src/Version/Controller/Element/CleanupController.php
  src/Version/Controller/Element/CollectionController.php
  src/Version/MappedParameter/VersionCleanupParameters.php
  src/Version/Repository/VersionRepository.php
  src/Version/Repository/VersionRepositoryInterface.php
  src/Version/Service/VersionService.php
  src/Version/Service/VersionServiceInterface.php
  src/Workflow/Controller/DetailsCollectionController.php
  src/Workflow/MappedParameter/WorkflowDetailsParameters.php
  src/Workflow/Service/WorkflowDetailsService.php
  src/Workflow/Service/WorkflowDetailsServiceInterface.php
  tests/Unit/Note/Service/FilterServiceTest.php
  tests/Unit/Workflow/Service/WorkflowDetailsServiceTest.php
Labels: Task

#100 [Task] Update response codes to enum values
  src/OpenApi/Attributes/Response/Error/BadRequestResponse.php
  src/OpenApi/Attributes/Response/Error/MethodNotAllowedResponse.php
  src/OpenApi/Attributes/Response/Error/NotCompletedResponse.php
  src/OpenApi/Attributes/Response/Error/NotFoundResponse.php
  src/OpenApi/Attributes/Response/Error/UnauthorizedResponse.php
  src/OpenApi/Attributes/Response/Error/UnprocessableContentResponse.php
  src/OpenApi/Attributes/Response/Error/UnsupportedMediaTypeResponse.php
  src/OpenApi/Attributes/Response/SuccessResponse.php
Labels: Task

#102 Update parameter validation
  src/Asset/Controller/CollectionController.php
  src/MappedParameter/CollectionParameters.php
  src/OpenApi/Attributes/Parameters/Query/PageParameter.php
  src/OpenApi/Attributes/Parameters/Query/PageSizeParameter.php
  src/OpenApi/Attributes/Parameters/Query/ParentIdParameter.php
Labels: Improvement

#105 [Task] Rename to resolver and add cache
  config/notes.yaml
  src/Note/Hydrator/NoteHydrator.php
  src/Note/Resolver/NoteDataResolver.php
  src/Note/Resolver/NoteDataResolverInterface.php
Labels: Task, Improvement

#108 [Task] Remove cache and rename params
  src/Note/Hydrator/NoteHydrator.php
  src/Note/Resolver/NoteDataResolver.php
  src/Note/Resolver/NoteDataResolverInterface.php
Labels: Task

#91 #110 Change auth to session.
  config/authorization.yaml
  config/pimcore/config.yaml
  config/pimcore/firewall.yaml
  config/pimcore/security.yaml
  doc/01_Installation.md
  src/Asset/Controller/CollectionController.php
  src/Asset/Controller/CustomSettingsController.php
  src/Asset/Controller/Data/TextController.php
  src/Asset/Controller/GetController.php
  src/Asset/Controller/UpdateController.php
  src/Authorization/Attributes/Response/InvalidCredentialsResponse.php
  src/Authorization/Controller/AuthorizationController.php
  src/Authorization/Controller/LoginController.php
  src/Authorization/Controller/LogoutController.php
  src/Authorization/EventSubscriber/LogoutSubscriber.php
  src/Authorization/Schema/Credentials.php
  src/Authorization/Schema/InvalidCredentials.php
  src/Authorization/Service/TokenService.php
  src/Authorization/Service/TokenServiceInterface.php
  src/Controller/AbstractApiController.php
  src/DataObject/Controller/CollectionController.php
  src/DataObject/Controller/GetController.php
  src/Dependency/Controller/Element/CollectionController.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/Exception/UnreachableException.php
  src/Note/Controller/CollectionController.php
  src/Note/Controller/DeleteController.php
  src/Note/Controller/Element/CollectionController.php
  src/Note/Controller/Element/CreateController.php
  src/OpenApi/Config/Security.php
  src/OpenApi/Schema/UserInformation.php
  src/Property/Controller/CollectionController.php
  src/Property/Controller/CreateController.php
  src/Property/Controller/DeleteController.php
  src/Property/Controller/Element/CollectionController.php
  src/Property/Controller/UpdateController.php
  src/Schedule/Controller/DeleteController.php
  src/Schedule/Controller/Element/CollectionController.php
  src/Schedule/Controller/Element/CreateController.php
  src/Schedule/Controller/Element/UpdateController.php
  src/Security/Service/SecurityService.php
  src/Security/Service/SecurityServiceInterface.php
  src/Security/Voter/AuthorizationVoter.php
  src/Security/Voter/PublicAuthorizationVoter.php
  src/Setting/Controller/GetController.php
  src/Translation/Controller/TranslationController.php
  src/User/Controller/CurrentUserController.php
  src/Version/Controller/Asset/DownloadController.php
  src/Version/Controller/Asset/ImageStreamController.php
  src/Version/Controller/DeleteController.php
  src/Version/Controller/Element/CleanupController.php
  src/Version/Controller/Element/CollectionController.php
  src/Version/Controller/GetController.php
  src/Version/Controller/PublishController.php
  src/Workflow/Controller/DetailsCollectionController.php
  src/Workflow/Controller/SubmitActionController.php
  tests/Unit/Dto/Token/CreateTest.php
  tests/Unit/Dto/Token/RefreshTest.php
  tests/Unit/Service/Security/SecurityServiceTest.php
Labels: Improvement

#116 Add attribute to check if version is published
  src/Version/Controller/Asset/DownloadController.php
  src/Version/Controller/Asset/ImageStreamController.php
  src/Version/Controller/DeleteController.php
  src/Version/Controller/Element/CleanupController.php
  src/Version/Controller/Element/CollectionController.php
  src/Version/Controller/GetController.php
  src/Version/Controller/PublishController.php
  src/Version/Hydrator/VersionHydrator.php
  src/Version/Hydrator/VersionHydratorInterface.php
  src/Version/Schema/Version.php
  src/Version/Service/VersionService.php
Labels: Improvement

#111 [Task] Update schema require
  src/Asset/Attributes/Request/UpdateAssetRequestBody.php
  src/Asset/Schema/Asset.php
  src/Asset/Schema/CustomSettings/FixedCustomSettings.php
  src/Asset/Schema/Type/Document.php
  src/Asset/Schema/Type/Image.php
  src/Asset/Schema/Type/Image/FocalPoint.php
  src/DataObject/Schema/DataObject.php
  src/Dependency/Schema/Dependency.php
  src/Note/Schema/CreateNote.php
  src/Note/Schema/Note.php
  src/OpenApi/Attributes/Response/Content/DataJson.php
  src/OpenApi/Attributes/Response/Content/IdJson.php
  src/OpenApi/Attributes/Response/Content/IdsJson.php
  src/OpenApi/Attributes/Response/Content/NameJson.php
  src/Property/Schema/ElementProperty.php
  src/Property/Schema/PredefinedProperty.php
  src/Property/Schema/UpdateElementProperty.php
  src/Property/Schema/UpdatePredefinedProperty.php
  src/Response/Element.php
  src/Response/Schema/DevError.php
  src/Response/Schema/Error.php
  src/Schedule/Schema/Schedule.php
  src/Schedule/Schema/UpdateSchedule.php
  src/Translation/Schema/Translation.php
  src/User/Schema/ResetPassword.php
  src/Workflow/Schema/AllowedTransition.php
  src/Workflow/Schema/GlobalAction.php
  src/Workflow/Schema/SubmitAction.php
  src/Workflow/Schema/WorkflowDetails.php
  src/Workflow/Schema/WorkflowStatus.php
Labels: Task

#122 [Task] Unify delete responses
  src/Note/Controller/DeleteController.php
  src/Property/Controller/DeleteController.php
  src/Schedule/Controller/DeleteController.php
  src/Version/Controller/DeleteController.php
Labels: Task, Improvement

#135 Get correct asset version size and dimensions
  src/Util/Traits/StreamedResponseTrait.php
  src/Version/Controller/Asset/DownloadController.php
  src/Version/Controller/Asset/ImageStreamController.php
  src/Version/Hydrator/AssetVersionHydrator.php
  src/Version/Hydrator/VersionHydrator.php
  src/Version/Schema/Version.php
  src/Version/Service/VersionBinaryService.php
  src/Version/Service/VersionDetailService.php
  src/Version/Service/VersionDetailServiceInterface.php
  tests/Unit/Version/Hydrator/AssetVersionHydratorTest.php
Labels: Task

#140 Workflow place label styling logic
  src/Workflow/Schema/WorkflowStatus.php
  src/Workflow/Service/WorkflowDetailsService.php
Labels: Improvement

#133 Adding permissions
  config/security.yaml
  src/Asset/Controller/Data/CustomMetadataController.php
  src/Asset/Controller/Data/CustomSettingsController.php
  src/Asset/Controller/Data/TextController.php
  src/Asset/Controller/DownloadController.php
  src/Asset/Controller/GetController.php
  src/Asset/Controller/UpdateController.php
  src/DataObject/Controller/CollectionController.php
  src/Dependency/Controller/Element/CollectionController.php
  src/Factory/QueryFactory.php
  src/Note/Controller/Element/CollectionController.php
  src/Note/Controller/Element/CreateController.php
  src/Property/Controller/CollectionController.php
  src/Property/Controller/CreateController.php
  src/Property/Controller/DeleteController.php
  src/Property/Controller/Element/CollectionController.php
  src/Property/Controller/UpdateController.php
  src/Property/Service/PropertyService.php
  src/Schedule/Controller/DeleteController.php
  src/Schedule/Controller/Element/CollectionController.php
  src/Schedule/Controller/Element/CreateController.php
  src/Schedule/Controller/Element/UpdateController.php
  src/Schedule/Repository/ScheduleRepository.php
  src/Security/Service/SecurityService.php
  src/Security/Service/SecurityServiceInterface.php
  src/Security/Voter/ElementTypePermissionVoter.php
  src/Translation/Controller/TranslationController.php
  src/Util/Constants/ElementTypes.php
  src/Util/Constants/UserPermissions.php
  tests/Unit/Service/Factory/QueryFactoryTest.php
Labels: Task, Improvement

#150 Add updater
  config/assets.yaml
  config/updater.yaml
  src/Asset/Attributes/Request/PatchAssetRequestBody.php
  src/Asset/Attributes/Request/UpdateAssetRequestBody.php
  src/Asset/Updater/Adapter/DataAdapter.php
  src/OpenApi/Attributes/Property/UpdateBooleanProperty.php
  src/OpenApi/Attributes/Property/UpdateIntegerProperty.php
  src/OpenApi/Attributes/Property/UpdateStringProperty.php
  src/Updater/Adapter/KeyAdapter.php
  src/Updater/Adapter/LockedAdapter.php
  src/Updater/Service/UpdateService.php
  src/User/Attributes/Request/CreateRequestBody.php
Labels: Task

#153 Asset download with GEE
  composer.json
  config/execution_engine.yaml
  config/pimcore/config.yaml
  config/pimcore/execution_engine.yaml
  src/Asset/Controller/CreateZipController.php
  src/Asset/Controller/DownloadZipController.php
  src/Asset/MappedParameter/CreateZipParameter.php
  src/Asset/Service/DownloadService.php
  src/Asset/Service/DownloadServiceInterface.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/Exception/Api/StreamResourceNotFoundException.php
  src/ExecutionEngine/AutomationAction/Messenger/Handler/ZipCollectionHandler.php
  src/ExecutionEngine/AutomationAction/Messenger/Handler/ZipCreationHandler.php
  src/ExecutionEngine/AutomationAction/Messenger/Messages/ZipCollectionMessage.php
  src/ExecutionEngine/AutomationAction/Messenger/Messages/ZipCreationMessage.php
  src/ExecutionEngine/EventSubscriber/ZipDownloadSubscriber.php
  src/ExecutionEngine/MappedParameter/ZipPathParameter.php
  src/ExecutionEngine/Service/ZipService.php
  src/ExecutionEngine/Service/ZipServiceInterface.php
  src/ExecutionEngine/Util/Jobs.php
  src/OpenApi/Attributes/Content/ScalarItemsJson.php
  src/PimcoreStudioBackendBundle.php
  src/Util/Traits/StreamedResponseTrait.php
Labels: New Feature

#156 Update schedule actions
  src/Schedule/Hydrator/ScheduleHydrator.php
  src/Schedule/Repository/ScheduleRepository.php
  src/Schedule/Schema/Schedule.php
  src/Schedule/Schema/UpdateSchedule.php
Labels: Task

#164 Make schemas public that use additional attributes
  src/Asset/Schema/Asset.php
  src/Asset/Schema/CustomSettings.php
  src/Note/Schema/Note.php
  src/Property/Schema/ElementProperty.php
  src/Property/Schema/PredefinedProperty.php
  src/Response/Element.php
  src/Schedule/Schema/Schedule.php
  src/Thumbnail/Schema/Thumbnail.php
  src/User/Schema/User.php
  src/User/Schema/UserPermission.php
  src/User/Schema/UserRole.php
  src/User/Schema/UserTreeNode.php
  src/Version/Schema/AssetVersion.php
  src/Version/Schema/DataObjectVersion.php
  src/Version/Schema/DocumentVersion.php
  src/Version/Schema/ImageVersion.php
  src/Version/Schema/Version.php
Labels: Task

#169 [Task] Thumbnail for versions
  src/Util/Traits/StreamedResponseTrait.php
  src/Version/Controller/Asset/ImageStreamController.php
  src/Version/Service/VersionBinaryService.php
  src/Version/Service/VersionBinaryServiceInterface.php
Labels: Task

#160 [Task] Add metadata to image version
  config/versions.yaml
  src/Version/Hydrator/AssetVersionHydrator.php
  src/Version/Hydrator/CustomMetadataVersionHydrator.php
  src/Version/Hydrator/CustomMetadataVersionHydratorInterface.php
  src/Version/Schema/CustomMetadataVersion.php
  src/Version/Schema/ImageVersion.php
  tests/Unit/Version/Hydrator/AssetVersionHydratorTest.php
Labels: Task

#173 [Task] Add username to schedule
  src/Schedule/Hydrator/ScheduleHydrator.php
  src/Schedule/Schema/Schedule.php
Labels: Task

#181 [Delete Info] Elements
  src/Element/Controller/DeleteInfoController.php
  src/Element/Schema/DeleteInfo.php
  src/Element/Service/ElementDeleteService.php
  src/Element/Service/ElementDeleteServiceInterface.php
Labels: New Feature

#188 Validate and use correct type for data objects
  src/Element/Controller/DeleteInfoController.php
  src/Element/Controller/GetIdByPathController.php
  src/MappedParameter/ElementTypeParameter.php
  src/Property/Controller/Element/CollectionController.php
  src/Schedule/Controller/Element/CollectionController.php
  src/Schedule/Controller/Element/CreateController.php
  src/Schedule/Controller/Element/UpdateController.php
Labels: Task

#192 [Task] Add Sort Order
  src/Asset/Service/AssetService.php
Labels: Task

#194 [Task] Clone Assets Follow up SSE
  config/assets.yaml
  config/pimcore/execution_engine.yaml
  src/Asset/EventSubscriber/CloneSubscriber.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Handler/AssetCloneHandler.php
  src/Asset/ExecutionEngine/AutomationAction/Messenger/Messages/AssetCloneMessage.php
  src/Asset/ExecutionEngine/Util/JobSteps.php
  src/Asset/Mercure/Events.php
  src/Asset/Service/ExecutionEngine/CloneService.php
  src/Mercure/Schema/ExecutionEngine/Finished.php
Labels: Task

#195 Validate thumbnail for image
  src/Asset/Service/DownloadService.php
Labels: Improvement

#198 [Task] Add SSE translations
  src/Asset/ExecutionEngine/Util/JobSteps.php
  src/ExecutionEngine/Util/Config.php
  src/ExecutionEngine/Util/Jobs.php
  translations/studio.en.yaml
Labels: Task
