Repository pimcore/studio-backend-bundle, pull requests merged in 2024-08, with the labels that each got.

#294 [OpenAPI] CLI command to generate json
  config/open_api.yaml
  doc/01_Installation.md
  src/OpenApi/Command/GenerateConfigJsonCommand.php
Labels: New Feature

#314 [Grid] Configuration ID as Query Parameter.
  src/Asset/Controller/Grid/Configuration/GetConfigurationController.php
  src/Asset/MappedParameter/GridConfigurationIdParameter.php
Labels: Bug

#321 [Asset Patch] Add possibility to add predefined metadata in patch
  src/Asset/Controller/PatchController.php
  src/Asset/Patcher/Adapter/MetadataAdapter.php
  src/Metadata/Repository/MetadataRepository.php
  src/Metadata/Repository/MetadataRepositoryInterface.php
  src/Patcher/Service/PatchService.php
  src/Patcher/Service/PatchServiceInterface.php
  src/Property/Hydrator/PropertyHydrator.php
  src/Property/Repository/PropertyRepository.php
  tests/Unit/Property/PropertyHydratorTest.php
Labels: Bug

#325 [Task] Add language matching
  src/Asset/Patcher/Adapter/MetadataAdapter.php
Labels: Task

#303 [Proposal] Make docs translatable
  src/Asset/Controller/CloneController.php
  src/Asset/Controller/UpdateController.php
  src/OpenApi/Config/Tags.php
  src/OpenApi/Controller/OpenApiController.php
  src/OpenApi/Service/OpenApiService.php
  src/OpenApi/Service/OpenApiServiceInterface.php
  src/Translation/Service/TranslatorService.php
  src/Translation/Service/TranslatorServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#327 Data Object Tree - Delete object
  config/assets.yaml
  config/elements.yaml
  config/pimcore/execution_engine.yaml
  src/Asset/ExecutionEngine/Util/JobSteps.php
  src/Asset/Service/ExecutionEngine/DeleteService.php
  src/DataObject/Controller/CloneController.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/Element/Controller/DeleteController.php
  src/Element/EventSubscriber/DeletionSubscriber.php
  src/Element/ExecutionEngine/AutomationAction/Messenger/Handler/ElementDeleteHandler.php
  src/Element/ExecutionEngine/AutomationAction/Messenger/Handler/RecycleBinHandler.php
  src/Element/ExecutionEngine/AutomationAction/Messenger/Messages/ElementDeleteMessage.php
  src/Element/ExecutionEngine/AutomationAction/Messenger/Messages/RecycleBinMessage.php
  src/Element/ExecutionEngine/Util/JobSteps.php
  src/Element/Service/ElementDeleteService.php
  src/Element/Service/ElementDeleteServiceInterface.php
  src/Element/Service/ExecutionEngine/DeleteService.php
  src/Element/Service/ExecutionEngine/DeleteServiceInterface.php
  src/ExecutionEngine/Util/Jobs.php
  translations/studio.en.yaml
  translations/studio_api_docs.en.yaml
Labels: New Feature

#328 [Task] Api Doc Translation
  src/Asset/Controller/Download/CreateCsvController.php
  src/Asset/Controller/Download/DownloadCsvController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#330 [Task] Api Doc Translation
  src/OpenApi/Config/Tags.php
  translations/studio_api_docs.en.yaml
Labels: Task

#309 [Icons] Data object tree - add icons
  src/Asset/Schema/Asset.php
  src/Asset/Schema/Type/Document.php
  src/Asset/Schema/Type/Image.php
  src/Asset/Schema/Type/Video.php
  src/DataIndex/Hydrator/Asset/ArchiveHydrator.php
  src/DataIndex/Hydrator/Asset/AudioHydrator.php
  src/DataIndex/Hydrator/Asset/DocumentHydrator.php
  src/DataIndex/Hydrator/Asset/FolderHydrator.php
  src/DataIndex/Hydrator/Asset/ImageHydrator.php
  src/DataIndex/Hydrator/Asset/TextHydrator.php
  src/DataIndex/Hydrator/Asset/UnknownHydrator.php
  src/DataIndex/Hydrator/Asset/VideoHydrator.php
  src/DataIndex/Hydrator/AssetHydrator.php
  src/DataIndex/Hydrator/DataObject/FolderHydrator.php
  src/DataIndex/Hydrator/DataObjectHydrator.php
  src/DataObject/Schema/DataObject.php
  src/Element/Schema/CustomAttributes.php
  src/Icon/Service/IconService.php
  src/Icon/Service/IconServiceInterface.php
  src/Response/Element.php
  src/Response/ElementIcon.php
  src/Util/Constants/ElementIconTypes.php
  src/Util/Constants/ElementTypes.php
Labels: Task

#334 [Api Translate] Unify translation keys for API docs
  src/Asset/Controller/CloneController.php
  src/Asset/Controller/Data/CustomMetadataController.php
  src/Asset/Controller/Data/CustomSettingsController.php
  src/Asset/Controller/Data/TextController.php
  src/Asset/Controller/Document/PreviewStreamController.php
  src/Asset/Controller/Download/CreateCsvController.php
  src/Asset/Controller/Download/CreateZipController.php
  src/Asset/Controller/Download/DeleteCsvController.php
  src/Asset/Controller/Download/DeleteZipController.php
  src/Asset/Controller/Download/DownloadCsvController.php
  src/Asset/Controller/Download/DownloadZipController.php
  src/Asset/Controller/DownloadController.php
  src/Asset/Controller/GetController.php
  src/Asset/Controller/Grid/Configuration/GetAvailableConfigurationController.php
  src/Asset/Controller/Grid/Configuration/GetConfigurationController.php
  src/Asset/Controller/Grid/GetController.php
  src/Asset/Controller/Image/CustomDownloadController.php
  src/Asset/Controller/Image/FormatDownloadController.php
  src/Asset/Controller/Image/ThumbnailDownloadController.php
  src/Asset/Controller/PatchController.php
  src/Asset/Controller/TreeController.php
  src/Asset/Controller/UpdateController.php
  src/Asset/Controller/Upload/AddController.php
  src/Asset/Controller/Upload/InfoController.php
  src/Asset/Controller/Upload/ReplaceController.php
  src/Asset/Controller/Upload/ZipController.php
  src/Asset/Controller/Video/ImageThumbnailStreamController.php
  src/Asset/Controller/Video/ThumbnailDownloadController.php
  src/Asset/Controller/Video/ThumbnailStreamController.php
  src/DataObject/Controller/CloneController.php
  src/DataObject/Controller/PatchController.php
  src/DataObject/Controller/UpdateController.php
  src/Element/Controller/DeleteController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#336 [Api Translate] Add translations for version endpoints
  src/Version/Attributes/Request/UpdateVersionRequestBody.php
  src/Version/Controller/Asset/DownloadController.php
  src/Version/Controller/Asset/ImageStreamController.php
  src/Version/Controller/Asset/PdfStreamController.php
  src/Version/Controller/DeleteController.php
  src/Version/Controller/Element/CleanupController.php
  src/Version/Controller/Element/CollectionController.php
  src/Version/Controller/GetController.php
  src/Version/Controller/PublishController.php
  src/Version/Controller/UpdateController.php
  src/Version/Schema/UpdateVersion.php
  translations/studio_api_docs.en.yaml
Labels: Task

#337 [Task] Translate notes
  src/Note/Controller/CollectionController.php
  src/Note/Controller/DeleteController.php
  src/Note/Controller/Element/CollectionController.php
  src/Note/Controller/Element/CreateController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#338 [Task] Translate settings descriptions
  src/Setting/Controller/GetController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#341 [Task] Add translations to schedule
  src/Schedule/Controller/DeleteController.php
  src/Schedule/Controller/Element/CollectionController.php
  src/Schedule/Controller/Element/CreateController.php
  src/Schedule/Controller/Element/UpdateController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#342 [Api Translate] Add missing translations for element and thumbnail endpoints
  src/Element/Controller/DeleteInfoController.php
  src/Element/Controller/FolderController.php
  src/Element/Controller/GetIdByPathController.php
  src/Thumbnail/Controller/ImageCollectionController.php
  src/Thumbnail/Controller/VideoCollectionController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#340 [Api Translate] Translate User and Role Section.
  src/Role/Controller/CloneController.php
  src/Role/Controller/CreateFolderController.php
  src/Role/Controller/CreateRoleController.php
  src/Role/Controller/DeleteFolderController.php
  src/Role/Controller/DeleteRoleController.php
  src/Role/Controller/GetRoleController.php
  src/Role/Controller/GetRolesController.php
  src/Role/Controller/RoleTreeController.php
  src/Role/Controller/UpdateRoleController.php
  src/User/Controller/CloneController.php
  src/User/Controller/CreateUserController.php
  src/User/Controller/CreateUserFolderController.php
  src/User/Controller/CurrentUserController.php
  src/User/Controller/DeleteUserController.php
  src/User/Controller/DeleteUserFolderController.php
  src/User/Controller/GetUserController.php
  src/User/Controller/GetUserPermissionsController.php
  src/User/Controller/ResetPasswordController.php
  src/User/Controller/UpdatePasswordController.php
  src/User/Controller/UpdateUserController.php
  src/User/Controller/UserTreeController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#343 [Api Translate] Add translations for email endpoints
  src/Email/Controller/Blocklist/AddController.php
  src/Email/Controller/Blocklist/CollectionController.php
  src/Email/Controller/Blocklist/DeleteController.php
  src/Email/Controller/CollectionController.php
  src/Email/Controller/DeleteController.php
  src/Email/Controller/Detail/EmailHtmlController.php
  src/Email/Controller/Detail/EmailParamsController.php
  src/Email/Controller/Detail/EmailTextController.php
  src/Email/Controller/Detail/GetController.php
  src/Email/Controller/ForwardController.php
  src/Email/Controller/ResendController.php
  src/Email/Controller/TestEmailController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#344 [Api Translate] Add translations for workflow
  src/Workflow/Controller/DetailsCollectionController.php
  src/Workflow/Controller/SubmitActionController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#348 [Api Translate] Add translations for asset endpoints
  src/Asset/Controller/Data/CustomMetadataController.php
  src/Asset/Controller/Data/CustomSettingsController.php
  src/Asset/Controller/Data/TextController.php
  src/Asset/Controller/Document/PreviewStreamController.php
  src/Asset/Controller/Download/CreateZipController.php
  src/Asset/Controller/Download/DeleteCsvController.php
  src/Asset/Controller/Download/DeleteZipController.php
  src/Asset/Controller/Download/DownloadZipController.php
  src/Asset/Controller/DownloadController.php
  src/Asset/Controller/GetController.php
  src/Asset/Controller/Grid/Configuration/GetAvailableConfigurationController.php
  src/Asset/Controller/Grid/Configuration/GetConfigurationController.php
  src/Asset/Controller/Grid/GetController.php
  src/Asset/Controller/Image/CustomDownloadController.php
  src/Asset/Controller/Image/FormatDownloadController.php
  src/Asset/Controller/Image/ThumbnailDownloadController.php
  src/Asset/Controller/TreeController.php
  src/Asset/Controller/Upload/AddController.php
  src/Asset/Controller/Upload/InfoController.php
  src/Asset/Controller/Upload/ReplaceController.php
  src/Asset/Controller/Upload/ZipController.php
  src/Asset/Controller/Video/ImageThumbnailStreamController.php
  src/Asset/Controller/Video/ThumbnailDownloadController.php
  src/Asset/Controller/Video/ThumbnailStreamController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#349 [Task] Final sort
  translations/studio_api_docs.en.yaml
Labels: Task

#356 241 bug when installing on a fresh pimcore instance the installer will cause an error
  src/DependencyInjection/Configuration.php
Labels: Pimcore:ToDo, Bug

#352 Notifications - Notification List
  config/notifications.yaml
  src/Notification/Controller/CollectionController.php
  src/Notification/Event/NotificationEvent.php
  src/Notification/Hydrator/NotificationHydrator.php
  src/Notification/Hydrator/NotificationHydratorInterface.php
  src/Notification/Repository/NotificationRepository.php
  src/Notification/Repository/NotificationRepositoryInterface.php
  src/Notification/Schema/NotificationListItem.php
  src/Notification/Service/NotificationService.php
  src/Notification/Service/NotificationServiceInterface.php
  src/OpenApi/Config/Tags.php
  src/Util/Constants/UserPermissions.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#360 Update tag create/update for unification with the rest
  src/Tag/Controller/DeleteController.php
  src/Tag/Controller/UpdateController.php
  src/Tag/Repository/TagRepository.php
  src/Tag/Repository/TagRepositoryInterface.php
  src/Tag/Service/TagService.php
  src/Tag/Service/TagServiceInterface.php
Labels: Improvement

#361 Notifications - Mark Notification as Read
  src/Notification/Controller/ReadController.php
  src/Notification/Service/NotificationService.php
  src/Notification/Service/NotificationServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#362 Remove unused parameters
  src/Tag/Controller/Element/CollectionController.php
Labels: Task

#366 #298 [Grid] Save grid configuration
  config/grid.yaml
  config/pimcore/config.yaml
  config/pimcore/doctrine.yaml
  src/Asset/Attributes/Property/SaveConfigurationColumn.php
  src/Asset/Attributes/Request/Grid/SaveConfigurationRequestBody.php
  src/Asset/Controller/Grid/Configuration/SaveConfigurationController.php
  src/Asset/MappedParameter/Grid/SaveConfigurationParameter.php
  src/Asset/Schema/Grid/ColumnSchema.php
  src/Asset/Service/AssetService.php
  src/Asset/Service/AssetServiceInterface.php
  src/Entity/Grid/GridConfiguration.php
  src/Entity/Grid/GridConfigurationFavorite.php
  src/Entity/Grid/GridConfigurationShare.php
  src/Grid/Repository/ConfigurationFavoriteRepository.php
  src/Grid/Repository/ConfigurationFavoriteRepositoryInterface.php
  src/Grid/Repository/ConfigurationRepository.php
  src/Grid/Repository/ConfigurationRepositoryInterface.php
  src/Grid/Schema/Filter.php
  src/Grid/Service/SaveConfigurationService.php
  src/Grid/Service/SaveConfigurationServiceInterface.php
  src/Installer.php
  src/OpenApi/Attributes/Property/ListOfInteger.php
  src/OpenApi/Attributes/Property/SingleBoolean.php
  translations/studio_api_docs.en.yaml
Labels: Task

#370 [Task] Introduce mapper
  config/listing.yaml
  src/Listing/Mapper/QueryToPayloadFilterMapper.php
  src/Listing/Mapper/QueryToPayloadFilterMapperInterface.php
  src/Listing/Service/ListingFilter.php
  src/Property/Controller/CollectionController.php
  src/Property/MappedParameter/PropertiesParameters.php
  src/Property/Repository/PropertyRepository.php
  src/Property/Repository/PropertyRepositoryInterface.php
  src/Property/Service/PropertyService.php
  src/Property/Service/PropertyServiceInterface.php
Labels: Task

#371 [Task] Add Defaultresponses
  src/Tag/Controller/CollectionController.php
  src/Tag/Controller/CreateController.php
  src/Tag/Controller/GetController.php
Labels: Task

#373 [Improvement] Use service locator for mapper
  config/listing.yaml
  src/DependencyInjection/CompilerPass/FilterMapperPass.php
  src/Listing/Mapper/FilterMapperInterface.php
  src/Listing/Service/FilterMapperService.php
  src/Listing/Service/FilterMapperServiceInterface.php
  src/PimcoreStudioBackendBundle.php
  src/Property/Mapper/PropertiesParametersMapper.php
  src/Property/Repository/PropertyRepository.php
Labels: Task, Improvement

#379 [CustomSettings]: Renamed meta data field
  src/Asset/Hydrator/CustomSettingsHydrator.php
  tests/Unit/Asset/Hydrator/CustomSettingsHydratorTest.php
Labels: Task

#378 [Grid] [OpenAPI] Refactoring
  config/assets.yaml
  config/grid.yaml
  src/Asset/Controller/Grid/Configuration/GetAvailableConfigurationController.php
  src/Asset/Controller/Grid/Configuration/GetConfigurationController.php
  src/Asset/Controller/Grid/Configuration/SaveConfigurationController.php
  src/Asset/Controller/Grid/GetController.php
  src/Asset/Service/Grid/SaveConfigurationService.php
  src/Asset/Service/Grid/SaveConfigurationServiceInterface.php
  src/DataObject/Controller/GetController.php
  src/DataObject/Controller/PatchController.php
  src/DataObject/Controller/TreeController.php
  src/DataObject/Controller/UpdateController.php
  src/ExecutionEngine/Controller/AbortController.php
  src/OpenApi/Config/Tags.php
  src/Thumbnail/Controller/ImageCollectionController.php
  src/Thumbnail/Controller/VideoCollectionController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#381 [Task] Documentation
  README.md
  doc/00_Installation.md
  doc/05_Addition_Attributes.md
  doc/10_Extending_Studio/01_Endpoints.md
  doc/10_Extending_Studio/02_OpenApi.md
  doc/10_Extending_Studio/03_Filters.md
  doc/10_Extending_Studio/04_Filters/01_OpenSearch_Filters.md
  doc/10_Extending_Studio/04_Filters/02_Listing_Filters.md
  doc/10_Extending_Studio/05_Grid.md
  doc/10_Extending_Studio/06_Update_Patch.md
  doc/10_Extending_Studio/README.md
Labels: Task

#385 [Task] Update Documentation for GEE and custom attributes
  README.md
  doc/04_Generic_Execution_Engine.md
  doc/05_Additional_Custom_Attributes.md
  src/Response/ElementIcon.php
Labels: Task

#387 [Notes] Note type endpoint
  config/pimcore/config.yaml
  doc/10_Extending_Studio/07_Notes.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/Note/Attribute/Response/Content/NoteTypesJson.php
  src/Note/Controller/Element/CollectionController.php
  src/Note/Controller/Element/TypeController.php
  src/Note/Event/NoteTypeEvent.php
  src/Note/Schema/NoteType.php
  src/Note/Schema/NoteTypeCollection.php
  src/Note/Service/NoteService.php
  src/Note/Service/NoteServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#389 [Task] Send notifications for events which need a followup action
  src/Asset/EventSubscriber/CsvCreationSubscriber.php
  src/Asset/EventSubscriber/ZipDownloadSubscriber.php
  src/ExecutionEngine/Service/EventSubscriberService.php
  src/ExecutionEngine/Service/EventSubscriberServiceInterface.php
  src/Mercure/Service/PublishService.php
  src/Mercure/Service/PublishServiceInterface.php
  src/Notification/Service/SendNotificationService.php
  src/Notification/Service/SendNotificationServiceInterface.php
Labels: Task

#392 [Versions] Detail Endpoint Improvements
  src/Response/Schemas.php
  src/Version/Event/ImageVersionEvent.php
  src/Version/Hydrator/AssetVersionHydrator.php
  src/Version/Hydrator/AssetVersionHydratorInterface.php
  src/Version/Schema/AssetVersion.php
  src/Version/Schema/ImageVersion.php
  src/Version/Service/VersionDetailService.php
  src/Version/Service/VersionDetailServiceInterface.php
  tests/Unit/Version/Hydrator/AssetVersionHydratorTest.php
Labels: Improvement
