Repository pimcore/studio-backend-bundle, pull requests merged in 2025-01, with the labels that each got.

#651 [Task] Add mimeType to asset grid options
  doc/10_Extending_Studio/05_Grid.md
  src/Grid/Mapper/ColumnMapper.php
  tests/Unit/Grid/Service/SystemColumnServiceTest.php
Labels: Task

#655 [Improvement] Use static
  src/Util/Trait/EnumToValueArrayTrait.php
Labels: Improvement

#666 [Improvement] Updating icon names
  src/Icon/Service/IconService.php
Labels: Pimcore:ToDo, Improvement

#669 [Improvement] Add required properties
  src/Tag/Schema/Tag.php
Labels: Improvement

#667 Add permissions and locked status to grid items
  src/Grid/Attribute/Property/GridCollection.php
  src/Grid/Service/GridService.php
  src/Response/Element.php
  src/Response/ElementInterface.php
Labels: Improvement

#673 [Improvement] Add path to video
  src/DataObject/Data/Adapter/ManyToOneRelationAdapter.php
  src/DataObject/Data/Adapter/VideoAdapter.php
Labels: Improvement

#665 [Improvement] Custom Reports tree endpoint
  config/custom_reports.yaml
  src/Asset/OpenApi/Attribute/Parameter/Path/NameParameter.php
  src/CustomReport/Controller/Config/TreeController.php
  src/CustomReport/Controller/GetController.php
  src/CustomReport/Controller/TreeController.php
  src/CustomReport/Hydrator/CustomReportHydrator.php
  src/CustomReport/Hydrator/CustomReportHydratorInterface.php
  src/CustomReport/Repository/CustomReportRepository.php
  src/CustomReport/Repository/CustomReportRepositoryInterface.php
  src/CustomReport/Schema/CustomReportColumnConfiguration.php
  src/CustomReport/Schema/CustomReportDetails.php
  src/CustomReport/Schema/CustomReportTreeConfigNode.php
  src/CustomReport/Schema/CustomReportTreeNode.php
  src/CustomReport/Service/CustomReportService.php
  src/CustomReport/Service/CustomReportServiceInterface.php
  src/OpenApi/Config/Tags.php
  src/Util/Constant/CustomReportPermissions.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#683 [Bug] Add loggedin check
  src/Security/Voter/PublicAuthorizationVoter.php
Labels: Bug

#679 [Improvement] Get fullpath for link
  src/DataObject/Data/Adapter/LinkAdapter.php
Labels: Improvement

#674 [Improvement] Change shape
  src/Tag/Service/TagService.php
Labels: Improvement

#685 [Bug] Fix empty permissions
  src/Role/Hydrator/RoleHydrator.php
  src/User/Hydrator/UserHydrator.php
  src/Util/Trait/PermissionSanitationTrait.php
Labels: Bug

#707 Update bundles
  composer.json
Labels: Task, Pimcore:ToDo

#698 [Improvement] Add id to schema
  src/OpenApi/Schema/UserInformation.php
  src/User/Hydrator/UserInformationHydrator.php
Labels: Improvement

#694 [Data Object] Provide properties for sorting
  src/DataIndex/Hydrator/DataObject/FolderHydrator.php
  src/DataIndex/Hydrator/DataObjectHydrator.php
  src/DataObject/Schema/DataObject.php
Labels: Improvement

#700 Make thumbnail clear available for images/videos/pdfs
  src/Asset/Controller/ThumbnailClearController.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#708 [Data Object][Versions] Adjust response data format of data object versions
  src/DataObject/Data/Adapter/BlockAdapter.php
  src/DataObject/Data/Adapter/ClassificationStoreAdapter.php
  src/DataObject/Data/Adapter/FieldCollectionsAdapter.php
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
  src/DataObject/Data/Adapter/ObjectBricksAdapter.php
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataService.php
  src/DataObject/Service/DataServiceInterface.php
  src/DataObject/Service/InheritanceService.php
  src/DataObject/Util/Trait/ValidateObjectDataTrait.php
  src/Icon/Service/IconService.php
  src/Icon/Service/IconServiceInterface.php
  src/Updater/Service/UpdateService.php
  src/Version/Event/AssetVersionEvent.php
  src/Version/Event/DataObjectVersionEvent.php
  src/Version/Event/DocumentVersionEvent.php
  src/Version/Hydrator/AssetVersionHydrator.php
  src/Version/Hydrator/DataObjectVersionHydrator.php
  src/Version/Hydrator/DocumentVersionHydrator.php
  src/Version/Schema/DataObjectVersion.php
  src/Version/Service/VersionDetailService.php
Labels: Task

#714 [Task] Switch to php8.3 for local tests.
  docker-compose.yml
Labels: Task

#713 [Task] Add Path formater Endpoint
  config/data_objects.yaml
  src/DataObject/Attribute/Request/PathFormatterRequestBody.php
  src/DataObject/Controller/PathFormatterController.php
  src/DataObject/Event/PreResponse/FormatedPathEvent.php
  src/DataObject/Hydrator/FormatedPathHydrator.php
  src/DataObject/Hydrator/FormatedPathHydratorInterface.php
  src/DataObject/Legacy/PathFormatterHelper.php
  src/DataObject/Legacy/PathFormatterHelperInterface.php
  src/DataObject/MappedParameter/PathFormatterParameter.php
  src/DataObject/Schema/FormatedPath.php
  src/DataObject/Service/PathFormatterService.php
  src/DataObject/Service/PathFormatterServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Task

#717 [Bug] Fix sorting by filesize.
  src/Grid/Mapper/ColumnMapper.php
  src/Grid/Service/SystemColumnService.php
  tests/Unit/Grid/Mapper/ColumnMapperTest.php
  tests/Unit/Grid/Service/SystemColumnServiceTest.php
Labels: Task

#715 Make classes public and add documentation
  doc/10_Extending_Studio/01_Endpoints.md
  doc/10_Extending_Studio/README.md
  src/Event/AbstractPreResponseEvent.php
  src/Response/Collection.php
  src/Util/Constant/HttpResponseCodes.php
Labels: Task, Pimcore:ToDo

#675 [Task][New feature] Object data preview
  config/data_objects.yaml
  src/DataObject/Attribute/Request/PreviewRequestBody.php
  src/DataObject/Controller/PreviewController.php
  src/DataObject/MappedParameter/PreviewParameter.php
  src/DataObject/Service/PreviewUrlService.php
  src/DataObject/Service/PreviewUrlServiceInterface.php
  src/OpenApi/Attribute/Response/RedirectResponse.php
  src/Util/Constant/HttpResponseCodes.php
  src/Util/Trait/RequestTrait.php
  translations/studio_api_docs.en.yaml
Labels: Task, New Feature

#718 [Improvement] Asset image add crop options to custom image thumbnail endpoint
  src/Asset/Controller/Image/CustomStreamController.php
  src/Asset/MappedParameter/ImageDownloadConfigParameter.php
  src/Asset/Service/ThumbnailService.php
  src/OpenApi/Attribute/Parameter/Query/BoolParameter.php
Labels: Improvement

#722 [Task] Add reflection-docblock
  composer.json
Labels: Task

#720 Check paths at a later stage
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/OpenApi/Service/OpenApiService.php
Labels: Improvement

#721 [Improvement] Switch from `GET` to `POST` for `notes`
  src/Note/Attribute/Request/NotesCollectionRequestBody.php
  src/Note/Controller/CollectionController.php
  src/Note/MappedParameter/NoteParameters.php
  tests/Unit/Note/Service/FilterServiceTest.php
Labels: Improvement

#724 [Task] Add preview generator
  composer.json
  config/data_objects.yaml
  src/DataObject/Legacy/PreviewGenerator.php
Labels: Task, Pimcore:ToDo

#727 [Grid] [Asset] Update Configuration shared User and role can be empty.
  src/Asset/MappedParameter/Grid/UpdateConfigurationParameter.php
Labels: Task

#729 [Task] Make 0 values possible
  src/Asset/MappedParameter/ImageDownloadConfigParameter.php
Labels: Improvement

#730 [Task] Change dataobject preview route to get
  src/DataObject/Controller/PreviewController.php
  src/OpenApi/Attribute/Parameter/Path/IntParameter.php
Labels: Task

#735 [Task] Switch to version loading
  config/data_objects.yaml
  src/DataObject/Service/PreviewUrlService.php
Labels: Task, Pimcore:ToDo

#736 Add custom reports to dependant bundles
  src/PimcoreStudioBackendBundle.php
Labels: Task, Pimcore:ToDo
