Repository pimcore/studio-backend-bundle, pull requests merged in 2025-06, with the labels that each got.

#1124 [Grid] [Data Objects] Advanced Columns - Transformers
  config/grid.yaml
  doc/03_Grid.md
  doc/10_Extending_Studio/05_Grid.md
  src/DependencyInjection/CompilerPass/TransformerPass.php
  src/Grid/Column/Collector/DataObject/AdvancedColumnCollector.php
  src/Grid/Column/Resolver/DataObject/AdvancedColumnResolver.php
  src/Grid/Column/Transformer/Lowercase.php
  src/Grid/Column/Transformer/Trim.php
  src/Grid/Column/Transformer/TrimEnd.php
  src/Grid/Column/Transformer/TrimStart.php
  src/Grid/Column/Transformer/Uppercase.php
  src/Grid/Column/TransformerInterface.php
  src/Grid/Schema/AdvancedColumnConfig/AdvancedColumnConfig.php
  src/Grid/Schema/AdvancedColumnConfig/Transformer.php
  src/Grid/Schema/Column.php
  src/Grid/Service/Loader/TaggedIteratorTransformerLoader.php
  src/Grid/Service/TransformerLoaderInterface.php
  src/PimcoreStudioBackendBundle.php
Labels: Task

#1130 [Document Tree] Sort order
  composer.json
  src/DataIndex/Query/DocumentQuery.php
  src/DataIndex/Query/DocumentQueryInterface.php
  src/Document/Controller/TreeController.php
  src/Document/Schema/Document.php
  src/Document/Schema/Type/Email.php
  src/Document/Schema/Type/Hardlink.php
  src/Document/Schema/Type/Link.php
  src/Document/Schema/Type/Page.php
  src/Document/Schema/Type/Snippet.php
  src/Document/Service/DocumentService.php
  src/Document/Service/HydratorService.php
Labels: Improvement

#1133 POCL Update June 2025
  LICENSE.md
Labels: Task

#1132 [Docs] Align Mercure settings with Symfony Cookie requirements
  doc/00_Installation.md
Labels: Improvement

#1142 [Documents][Tree]: Add navigation exclude property
  src/Document/Schema/Document.php
  src/Document/Service/HydratorService.php
Labels: Improvement

#1145 [Documents][Tree] Sorting
  src/DataIndex/Query/TreeQuery.php
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataObjectServiceInterface.php
  src/Document/Service/DocumentService.php
Labels: Improvement

#1153 [Task] Advanced Columns improvement
  config/grid.yaml
  config/pimcore/config.yaml
  doc/03_Grid.md
  doc/10_Extending_Studio/05_Grid.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/Exception/Api/TransformerException.php
  src/Grid/Column/Collector/DataObject/AdvancedColumnCollector.php
  src/Grid/Column/Resolver/DataObject/AdvancedColumnResolver.php
  src/Grid/Column/Transformer/CaseChange.php
  src/Grid/Column/Transformer/Combine.php
  src/Grid/Column/Transformer/Lowercase.php
  src/Grid/Column/Transformer/Trim.php
  src/Grid/Column/Transformer/TrimEnd.php
  src/Grid/Column/Transformer/TrimStart.php
  src/Grid/Column/Transformer/Uppercase.php
  src/Grid/Column/TransformerInterface.php
  src/Grid/Schema/AdvancedColumnConfig/AdvancedColumnConfig.php
  src/Grid/Schema/AdvancedColumnConfig/ExistingColumnConfig.php
  src/Grid/Schema/AdvancedColumnConfig/Transformer.php
  src/Grid/Schema/Column.php
  src/Grid/Util/AdvancedValue.php
Labels: Improvement

#1157 [Task] Fix Schema Validation.
  src/Asset/Controller/Grid/Configuration/DeleteConfigurationController.php
  src/Asset/Controller/Grid/Configuration/SaveConfigurationController.php
  src/Asset/Schema/Type/Image/FocalPoint.php
  src/Class/Schema/ClassDefinition.php
  src/Class/Schema/ClassDefinitionList.php
  src/Class/Schema/CustomLayout/CustomLayout.php
  src/Class/Schema/CustomLayout/CustomLayoutCompact.php
  src/Class/Schema/CustomLayout/CustomLayoutNew.php
  src/Class/Schema/FieldCollection/LayoutDefinition.php
  src/Class/Schema/ObjectBrick/LayoutDefinition.php
  src/CustomReport/Attribute/Request/CsvExportRequestBody.php
  src/CustomReport/Controller/Chart/GetController.php
  src/CustomReport/Schema/CustomReportChartData.php
  src/CustomReport/Schema/CustomReportDetails.php
  src/CustomReport/Service/CustomReportService.php
  src/CustomReport/Service/CustomReportServiceInterface.php
  src/DataObject/Attribute/Request/PathFormatterRequestBody.php
  src/DataObject/Controller/LayoutController.php
  src/DataObject/MappedParameter/GetLayoutIdParameter.php
  src/Dependency/Schema/Dependency.php
  src/Document/Schema/DocTypeType.php
  src/Document/Schema/DocTypeUpdateParameters.php
  src/Document/Schema/Document.php
  src/Document/Schema/PageSnippet/Controller.php
  src/Document/Schema/PageSnippet/Template.php
  src/Document/Schema/Translation/TranslationLink.php
  src/Document/Schema/Translation/TranslationLinks.php
  src/Document/Schema/Translation/TranslationParent.php
  src/Document/Schema/UpdateSiteParameters.php
  src/Email/Schema/ObjectParameter.php
  src/Grid/Schema/AdvancedColumnConfig/AdvancedColumnConfig.php
  src/Mercure/Schema/ExecutionEngine/Finished.php
  src/OpenApi/Attribute/Parameter/Query/IntParameter.php
  src/OpenApi/Config/Spec.php
  src/Response/Element.php
  src/Role/Schema/DetailedRole.php
  src/Role/Schema/SimpleRole.php
  src/Role/Schema/UpdateRole.php
  src/Schedule/Schema/Schedule.php
  src/Schedule/Schema/UpdateSchedule.php
  src/Search/Schema/Document/PageSearchPreview.php
  src/Unit/Attribute/Response/ConvertedValueJson.php
  src/Unit/Schema/ConvertedQuantityValue.php
  src/User/Schema/SimpleUser.php
  src/User/Schema/UpdateUser.php
  src/User/Schema/UpdateUserProfile.php
  src/User/Schema/User.php
  src/Workflow/Schema/SubmitAction.php
Labels: Task

#1160 [Website Settings] Fix type schema
  src/WebsiteSetting/Controller/ListTypeController.php
Labels: Improvement

#1161 [Recycle bin] Add endpoints to restore and delete items
  config/assets.yaml
  config/pimcore/execution_engine.yaml
  config/recycle_bin.yaml
  src/ExecutionEngine/Util/Config.php
  src/ExecutionEngine/Util/Jobs.php
  src/MappedParameter/ItemsParameter.php
  src/RecycleBin/Controller/DeleteController.php
  src/RecycleBin/Controller/RestoreController.php
  src/RecycleBin/EventSubscriber/DeleteItemsSubscriber.php
  src/RecycleBin/EventSubscriber/RestoreItemsSubscriber.php
  src/RecycleBin/ExecutionEngine/Handler/DeleteItemsHandler.php
  src/RecycleBin/ExecutionEngine/Handler/RestoreItemsHandler.php
  src/RecycleBin/ExecutionEngine/Messages/DeleteItemsMessage.php
  src/RecycleBin/ExecutionEngine/Messages/RestoreItemsMessage.php
  src/RecycleBin/ExecutionEngine/Util/JobSteps.php
  src/RecycleBin/Mercure/Events.php
  src/RecycleBin/Mercure/Provider/RecycleBinTopicProvider.php
  src/RecycleBin/Service/JobService.php
  src/RecycleBin/Service/JobServiceInterface.php
  src/RecycleBin/Service/RecycleBinService.php
  src/RecycleBin/Service/RecycleBinServiceInterface.php
  translations/studio.en.yaml
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1170 [Email] Add elementType to objectData
  src/Email/Schema/ObjectParameter.php
  src/Email/Service/EmailLogService.php
Labels: Improvement

#1173 [Application Logger]: Add endpoints to list data for filters
  src/Bundle/ApplicationLogger/Attribute/Content/ComponentsJson.php
  src/Bundle/ApplicationLogger/Attribute/Content/PrioritiesJson.php
  src/Bundle/ApplicationLogger/Controller/ListComponentsController.php
  src/Bundle/ApplicationLogger/Controller/ListPrioritiesController.php
  src/Bundle/ApplicationLogger/Repository/LogRepository.php
  src/Bundle/ApplicationLogger/Repository/LogRepositoryInterface.php
  src/Bundle/ApplicationLogger/Service/LogService.php
  src/Bundle/ApplicationLogger/Service/LogServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1174 [Task] Prepare release for 0.6.30
  composer.json
  src/OpenApi/Config/Spec.php
Labels: Task
