Repository pimcore/studio-backend-bundle, pull requests merged in 2025-02, with the labels that each got.

#739 [Data Objects] Add adapters logic for patching
  config/data_objects.yaml
  src/DataObject/Data/Adapter/AdvancedManyToManyObjectRelationAdapter.php
  src/DataObject/Data/Adapter/AdvancedManyToManyRelationAdapter.php
  src/DataObject/Data/Adapter/BlockAdapter.php
  src/DataObject/Data/Adapter/BooleanAdapter.php
  src/DataObject/Data/Adapter/CalculatedValueAdapter.php
  src/DataObject/Data/Adapter/ClassificationStoreAdapter.php
  src/DataObject/Data/Adapter/ConsentAdapter.php
  src/DataObject/Data/Adapter/DateAdapter.php
  src/DataObject/Data/Adapter/DateRangeAdapter.php
  src/DataObject/Data/Adapter/EncryptedFieldAdapter.php
  src/DataObject/Data/Adapter/ExternalImageAdapter.php
  src/DataObject/Data/Adapter/FieldCollectionsAdapter.php
  src/DataObject/Data/Adapter/GeoBoundsAdapter.php
  src/DataObject/Data/Adapter/GeoPointAdapter.php
  src/DataObject/Data/Adapter/GeoPointsAdapter.php
  src/DataObject/Data/Adapter/HotspotImageAdapter.php
  src/DataObject/Data/Adapter/ImageAdapter.php
  src/DataObject/Data/Adapter/ImageGalleryAdapter.php
  src/DataObject/Data/Adapter/InputQuantityValueAdapter.php
  src/DataObject/Data/Adapter/LinkAdapter.php
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
  src/DataObject/Data/Adapter/ManyToManyObjectRelationAdapter.php
  src/DataObject/Data/Adapter/ManyToManyRelationAdapter.php
  src/DataObject/Data/Adapter/ManyToOneRelationAdapter.php
  src/DataObject/Data/Adapter/MultiSelectAdapter.php
  src/DataObject/Data/Adapter/NumericAdapter.php
  src/DataObject/Data/Adapter/NumericRangeAdapter.php
  src/DataObject/Data/Adapter/ObjectBricksAdapter.php
  src/DataObject/Data/Adapter/QuantityValueAdapter.php
  src/DataObject/Data/Adapter/QuantityValueRangeAdapter.php
  src/DataObject/Data/Adapter/ReverseObjectRelationAdapter.php
  src/DataObject/Data/Adapter/RgbaColorAdapter.php
  src/DataObject/Data/Adapter/SelectAdapter.php
  src/DataObject/Data/Adapter/SliderAdapter.php
  src/DataObject/Data/Adapter/StringAdapter.php
  src/DataObject/Data/Adapter/StructuredTableAdapter.php
  src/DataObject/Data/Adapter/TableAdapter.php
  src/DataObject/Data/Adapter/UrlSlugAdapter.php
  src/DataObject/Data/Adapter/VideoAdapter.php
  src/DataObject/Data/Model/FieldContextData.php
  src/DataObject/Data/SetterDataInterface.php
  src/DataObject/Schema/DataObject.php
  src/DataObject/Service/Data/RelationDataService.php
  src/DataObject/Service/Data/RelationDataServiceInterface.php
  src/DataObject/Service/InheritanceService.php
  src/DataObject/Service/InheritanceServiceInterface.php
  src/DataObject/Util/Trait/RelationDataTrait.php
  src/DataObject/Util/Trait/ValidateObjectDataTrait.php
  src/Patcher/Service/PatchService.php
  src/Patcher/Service/PatchServiceInterface.php
  src/Util/Constant/Asset/SubTypes.php
  src/Util/Constant/DataObject/FieldKeys.php
  src/Util/Constant/PatchDataKeys.php
  src/Util/Constant/PatcherActions.php
Labels: New Feature

#742 [Data Objects] Consider custom layouts in the data object layout endpoint
  config/data_objects.yaml
  config/security.yaml
  src/Class/Controller/CustomLayout/EditorCollectionController.php
  src/Class/Service/CustomLayoutService.php
  src/Class/Service/CustomLayoutServiceInterface.php
  src/DataObject/Controller/LayoutController.php
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
  src/DataObject/Hydrator/ObjectLayoutHydrator.php
  src/DataObject/Hydrator/ObjectLayoutHydratorInterface.php
  src/DataObject/MappedParameter/LayoutIdParameter.php
  src/DataObject/Service/LayoutService.php
  src/DataObject/Service/LayoutServiceInterface.php
  src/Security/Service/LayoutService.php
  src/Security/Service/LayoutServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#746 [Bug] Page preview route name
  src/Document/Controller/Page/PreviewStreamController.php
Labels: Bug

#747 [Grid] [DataObject] Get Grid Data
  config/grid.yaml
  src/DataObject/Controller/Grid/GetController.php
  src/Filter/MappedParameter/FilterParameter.php
  src/Grid/Column/Collector/DataObject/FieldDefinitionCollector.php
  src/Grid/Column/Collector/DataObject/ObjectBrickCollector.php
  src/Grid/Column/Resolver/DataObject/AdapterResolver.php
  src/Grid/Schema/ColumnData.php
  src/Grid/Service/ColumnConfigurationService.php
  src/Grid/Service/ColumnConfigurationServiceInterface.php
  src/Grid/Service/GridService.php
  src/Grid/Service/GridServiceInterface.php
  src/Grid/Util/Trait/ColumnDataTrait.php
  src/Grid/Util/Trait/LocalizedValueTrait.php
Labels: Improvement

#749 [Bug] Add missing classId Parameter
  src/DataObject/Controller/Grid/GetAvailableColumnsController.php
  src/DataObject/Controller/Grid/GetController.php
Labels: Bug

#751 [Data Objects] Add endpoint to list all class definitions
  config/class.yaml
  src/Class/Controller/CollectionController.php
  src/Class/Event/ClassDefinitionListEvent.php
  src/Class/Hydrator/ClassDefinitionHydrator.php
  src/Class/Hydrator/ClassDefinitionListHydrator.php
  src/Class/Hydrator/ClassDefinitionListHydratorInterface.php
  src/Class/Schema/ClassDefinition.php
  src/Class/Schema/ClassDefinitionList.php
  src/Class/Service/ClassDefinitionService.php
  src/Class/Service/ClassDefinitionServiceInterface.php
  src/Icon/Service/IconService.php
  src/Icon/Service/IconServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#752 [Elements] Add endpoint to list context permissions
  config/notes.yaml
  src/Element/Attribute/Response/Content/OneOfContextPermissionsJson.php
  src/Element/Controller/GetContextPermissionsController.php
  src/Element/Event/PreResponse/ElementContextPermissionsEvent.php
  src/Element/Schema/Permissions/AssetContextPermissions.php
  src/Element/Schema/Permissions/DataObjectContextPermissions.php
  src/Element/Schema/Permissions/DocumentContextPermissions.php
  src/Element/Service/ElementService.php
  src/Element/Service/ElementServiceInterface.php
  src/Response/Schemas.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#761 [Task] Add possiblity to add errorKey to error response
  src/EventSubscriber/ApiExceptionSubscriber.php
  src/Exception/Api/AbstractApiException.php
  src/Util/Constant/HttpResponseErrorKeys.php
  translations/studio_api_docs.en.yaml
Labels: Task, Pimcore:ToDo

#762 [Grid] [DataObject] Use SortFilter for DataObject as well
  config/data_index_filters.yaml
  src/DataIndex/Filter/SortFilter.php
  src/DataIndex/Query/AssetQueryInterface.php
  src/DataIndex/Query/DataObjectQuery.php
  src/DataIndex/Query/QueryInterface.php
  tests/Unit/DataIndex/Filter/SortFilterTest.php
Labels: Task

#759 [Task] Change response code
  src/Element/Service/ElementFolderService.php
  src/Exception/Api/ElementExistsException.php
  src/Util/Constant/HttpResponseCodes.php
  src/Util/Constant/HttpResponseErrorKeys.php
  translations/studio_api_docs.en.yaml
Labels: Task

#772 [Task] Open element
  doc/10_Extending_Studio/08_Events.md
  src/DataIndex/AssetSearchService.php
  src/DataIndex/AssetSearchServiceInterface.php
  src/DataIndex/DataObjectSearchService.php
  src/DataIndex/DataObjectSearchServiceInterface.php
  src/DataIndex/DocumentSearchService.php
  src/DataIndex/DocumentSearchServiceInterface.php
  src/DataIndex/ElementSearchService.php
  src/DataIndex/ElementSearchServiceInterface.php
  src/DataObject/Legacy/ApplyChangesHelper.php
  src/Element/Controller/ResolveBySearchTermController.php
  src/Element/Event/PreResolve/ElementResolveEvent.php
  src/Element/Request/SearchTermParameter.php
  src/Element/Service/ElementService.php
  src/Element/Service/ElementServiceInterface.php
  src/Element/Util/Trait/SearchTermTrait.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#779 [Task] Add draft data
  src/DataObject/Schema/DataObject.php
  src/DataObject/Schema/DataObjectDraftData.php
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataService.php
  src/DataObject/Service/DataServiceInterface.php
  src/DataObject/Service/LayoutService.php
  src/Util/Trait/ElementProviderTrait.php
  src/Workflow/Service/WorkflowDetailsService.php
Labels: Task, Pimcore:ToDo

#778 [Data Object Editor] Layout endpoint should return main class layout by default
  src/DataObject/Controller/LayoutController.php
  src/DataObject/Service/LayoutService.php
  src/DataObject/Service/LayoutServiceInterface.php
Labels: Improvement

#784 [Data Object] Set draft data only for data object detail
  src/DataObject/Service/DataService.php
Labels: Task

#782 [Widgets]: Unify widget route with other routes
  src/Perspective/Controller/Widget/AddController.php
  src/Perspective/Controller/Widget/CollectionConfigurationController.php
  src/Perspective/Controller/Widget/TypeController.php
Labels: Task

#787 [Widgets] Remove unnecessary parameters from widgets configuration
  src/DependencyInjection/Configuration.php
  src/Perspective/Hydrator/ElementTreeWidgetConfigHydrator.php
  src/Perspective/Schema/ElementTreeWidgetConfig.php
  src/Perspective/Schema/SaveElementTreeWidgetConfig.php
  src/Perspective/Service/WidgetValidationService.php
Labels: Task

#792 [Versions] Add permission check for auto safe delete
  src/Version/Controller/DeleteController.php
  src/Version/Service/VersionService.php
  src/Version/Service/VersionServiceInterface.php
Labels: Improvement

#795 [Task] Upgrade nesbot/carbon to match admin-ui
  composer.json
Labels: Task

#783 [Grid] [Data Object] Save Grid Configuration
  config/assets.yaml
  config/grid.yaml
  src/Asset/Attribute/Request/Grid/UpdateConfigurationRequestBody.php
  src/Asset/Controller/Grid/Configuration/UpdateConfigurationController.php
  src/Asset/MappedParameter/Grid/UpdateConfigurationParameter.php
  src/Asset/Service/Grid/SaveConfigurationService.php
  src/Asset/Service/Grid/UpdateConfigurationService.php
  src/Asset/Service/Grid/UpdateConfigurationServiceInterface.php
  src/DataObject/Controller/Grid/Configuration/SaveConfigurationController.php
  src/Entity/Grid/GridConfiguration.php
  src/Entity/Grid/GridConfigurationFavorite.php
  src/Grid/Attribute/Request/ConfigurationRequestBody.php
  src/Grid/MappedParameter/ConfigurationParameter.php
  src/Grid/MappedParameter/ConfigurationParameterInterface.php
  src/Grid/Repository/ConfigurationFavoriteRepository.php
  src/Grid/Repository/ConfigurationFavoriteRepositoryInterface.php
  src/Grid/Service/FavoriteService.php
  src/Grid/Service/FavoriteServiceInterface.php
  src/Grid/Service/SaveConfigurationService.php
  src/Grid/Service/SaveConfigurationServiceInterface.php
  src/Grid/Service/UserRoleShareService.php
  src/Grid/Service/UserRoleShareServiceInterface.php
  src/Installer.php
  translations/studio_api_docs.en.yaml
Labels: Task

#803 [Grid] [Data Object] Delete configuration endpoint.
  src/DataObject/Controller/Grid/Configuration/DeleteConfigurationController.php
  src/Grid/Service/ConfigurationService.php
  src/Grid/Service/ConfigurationServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Task

#817 [Task] Add container extension
  src/PimcoreStudioBackendBundle.php
Labels: Task, Pimcore:ToDo

#812 [Element Tree] Locate element in the tree
  config/data_index.yaml
  config/elements.yaml
  config/perspectives.yaml
  doc/05_Additional_Custom_Attributes.md
  src/DataIndex/Adapter/AssetSearchAdapter.php
  src/DataIndex/Adapter/AssetSearchAdapterInterface.php
  src/DataIndex/Adapter/DataObjectSearchAdapter.php
  src/DataIndex/Adapter/DataObjectSearchAdapterInterface.php
  src/DataIndex/Adapter/DocumentSearchAdapter.php
  src/DataIndex/Adapter/DocumentSearchAdapterInterface.php
  src/DataIndex/AssetSearchService.php
  src/DataIndex/AssetSearchServiceInterface.php
  src/DataIndex/DataObjectSearchService.php
  src/DataIndex/DataObjectSearchServiceInterface.php
  src/DataIndex/DocumentSearchService.php
  src/DataIndex/DocumentSearchServiceInterface.php
  src/DataIndex/ElementSearchService.php
  src/DataIndex/ElementSearchServiceInterface.php
  src/DataIndex/Query/AssetQuery.php
  src/DataIndex/Query/DataObjectQuery.php
  src/DataIndex/Query/DocumentQuery.php
  src/DataIndex/Query/QueryInterface.php
  src/DataIndex/Query/TreeQuery.php
  src/DataIndex/Query/TreeQueryInterface.php
  src/DataIndex/Request/DataObjectParameters.php
  src/DataIndex/Request/ElementParameters.php
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataObjectServiceInterface.php
  src/Element/Controller/GetElementTreeLocationController.php
  src/Element/Event/PreResponse/ElementLocateEvent.php
  src/Element/Schema/LocationData.php
  src/Element/Schema/TreeLevelData.php
  src/Element/Service/ElementLocationService.php
  src/Element/Service/ElementLocationServiceInterface.php
  src/Perspective/Hydrator/PerspectiveConfigHydratorInterface.php
  src/Perspective/Model/WidgetElementData.php
  src/Perspective/Repository/ElementTreeWidgetRepository.php
  src/Perspective/Repository/ElementTreeWidgetRepositoryInterface.php
  src/Perspective/Service/PerspectiveService.php
  src/Perspective/Service/PerspectiveServiceInterface.php
  src/Setting/Service/SettingsService.php
  src/Setting/Service/SettingsServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#821 [Data Object Grid] Add published to Grid
  config/grid.yaml
  src/Grid/Column/ColumnType.php
  src/Grid/Column/Definition/System/BooleanDefinition.php
  src/Grid/Column/FrontendType.php
  src/Grid/Column/Resolver/System/BooleanResolver.php
Labels: Task

#822 [Element Tree Widgets] Add options to define custom page size
  doc/10_Extending_Studio/05_Perspectives/01_Widgets.md
  src/DataIndex/Query/TreeQuery.php
  src/DependencyInjection/Configuration.php
  src/Perspective/Hydrator/ElementTreeWidgetConfigHydrator.php
  src/Perspective/Schema/ElementTreeWidgetConfig.php
  src/Perspective/Schema/SaveElementTreeWidgetConfig.php
  src/Perspective/Service/WidgetValidationService.php
Labels: New Feature

#827 [Perspectives] Add endpoint to create new perspective
  src/Perspective/Attribute/Request/AddPerspectiveRequestBody.php
  src/Perspective/Controller/AddController.php
  src/Perspective/Repository/PerspectiveConfigRepository.php
  src/Perspective/Repository/PerspectiveConfigRepositoryInterface.php
  src/Perspective/Schema/AddPerspectiveConfig.php
  src/Perspective/Schema/SavePerspectiveConfig.php
  src/Perspective/Service/PerspectiveService.php
  src/Perspective/Service/PerspectiveServiceInterface.php
  src/Perspective/Service/PerspectiveValidationService.php
  src/Perspective/Service/PerspectiveValidationServiceInterface.php
  src/Perspective/Service/WidgetService.php
  src/Util/Trait/ValidateConfigurationTrait.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#833 [Perspectives] Add default widget icon and add PQL filter in asset tree
  config/pimcore/default_perspective.yaml
  src/Asset/Controller/TreeController.php
Labels: Task

#837 [Perspectives] Update perspective configuration
  src/Perspective/Attribute/Request/SavePerspectiveRequestBody.php
  src/Perspective/Controller/UpdateController.php
  src/Perspective/Hydrator/PerspectiveConfigDetailHydrator.php
  src/Perspective/Schema/PerspectiveConfigDetail.php
  src/Perspective/Service/PerspectiveService.php
  src/Perspective/Service/PerspectiveServiceInterface.php
  src/Perspective/Service/PerspectiveValidationService.php
  src/Perspective/Service/PerspectiveValidationServiceInterface.php
  src/Perspective/Service/WidgetService.php
  src/Perspective/Service/WidgetServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#838 [Tree Widget] Add rootFolderId
  src/Document/Service/SiteService.php
  src/Perspective/Controller/Widget/GetConfigurationController.php
  src/Perspective/Hydrator/ElementTreeWidgetConfigHydrator.php
  src/Perspective/Schema/ElementTreeWidgetConfig.php
  src/Perspective/Service/WidgetService.php
  src/Perspective/Service/WidgetServiceInterface.php
  src/Perspective/Service/WidgetValidationService.php
  src/Util/Constant/ElementFolderIds.php
  src/Util/Constant/ElementFolderPaths.php
Labels: Improvement

#842 [Tree Widgets] Cleanup element context permissions
  doc/10_Extending_Studio/05_Perspectives/01_Widgets.md
  src/Element/Hydrator/Permissions/AssetContextPermissionHydrator.php
  src/Element/Hydrator/Permissions/DataObjectContextPermissionHydrator.php
  src/Element/Hydrator/Permissions/DocumentContextPermissionHydrator.php
  src/Element/Schema/Permissions/SaveAssetContextPermissions.php
  src/Element/Schema/Permissions/SaveDataObjectContextPermissions.php
  src/Element/Schema/Permissions/SaveDocumentContextPermissions.php
Labels: Task

#845 [Data Object Editor] Problem with publish task after autoSave
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
  src/DataObject/Legacy/PreviewGenerator.php
  src/DataObject/Service/DataService.php
  src/DataObject/Service/DataServiceInterface.php
  src/Element/Service/ElementSaveService.php
  src/Updater/Service/UpdateService.php
  src/Updater/Service/UpdateServiceInterface.php
  src/Util/Constant/ElementSaveTasks.php
Labels: Task

#850 [Tree Widget] Add asset downloadZip tree context permission
  src/Element/Hydrator/Permissions/AssetContextPermissionHydrator.php
  src/Element/Schema/Permissions/SaveAssetContextPermissions.php
Labels: Task

#852 [Docs]: Fix ContextPermissionsServiceInterface class reference in the docs
  doc/10_Extending_Studio/09_Perspectives.md
Labels: Task

#856 [Data Object Editor] Problem with publish task after autoSave
  src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php
Labels: Task
