Repository pimcore/studio-backend-bundle, pull requests merged in 2025-07, with the labels that each got.

#1166 [Task] Various Changes
  src/Asset/Controller/Image/CustomStreamController.php
  src/Asset/Controller/Video/ImageThumbnailStreamController.php
  src/Asset/MappedParameter/ImageDownloadConfigParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/AspectRatioParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/ContainParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/CoverParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/ForceResizeParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/FrameParameter.php
  src/Asset/OpenApi/Attribute/Parameter/Query/ImageConfigParameter.php
  src/CustomReport/Attribute/Request/CsvExportRequestBody.php
  src/EventSubscriber/ApiExceptionSubscriber.php
  src/Exception/Api/InvalidActionTypeException.php
  src/Exception/Api/InvalidArgumentException.php
  src/Exception/Api/InvalidAssetFormatTypeException.php
  src/Exception/Api/InvalidDataTypeException.php
  src/Exception/Api/InvalidDependencyMode.php
  src/Exception/Api/InvalidElementTypeException.php
  src/Exception/Api/InvalidFilterException.php
  src/Exception/Api/InvalidFilterServiceTypeException.php
  src/Exception/Api/InvalidLocaleException.php
  src/Exception/Api/InvalidParentIdException.php
  src/Exception/Api/InvalidThumbnailConfigurationException.php
  src/Exception/Api/InvalidThumbnailException.php
  src/Grid/Attribute/Request/GridRequestBody.php
  src/Grid/Schema/Column.php
  src/OpenApi/Attribute/Parameter/Query/BoolParameter.php
  src/OpenApi/Attribute/Parameter/Query/IntParameter.php
  src/OpenApi/Attribute/Parameter/Query/TextFieldParameter.php
  src/Unit/Attribute/Parameter/Query/ValueParameter.php
Labels: Task

#1178 [Notifications] Endpoint for unread notifications count
  src/Notification/Controller/GetUnreadCountController.php
  src/Notification/Repository/NotificationRepository.php
  src/Notification/Repository/NotificationRepositoryInterface.php
  src/Notification/Schema/UnreadCount.php
  src/Notification/Service/NotificationService.php
  src/Notification/Service/NotificationServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Task

#1181 [Task] Update Schema
  src/Bundle/Seo/Schema/RedirectUpdateParameters.php
Labels: Task

#1184 [Redirects] Add import/export and cleanup endpoints
  config/bundle_seo.yaml
  doc/05_Additional_Custom_Attributes.md
  src/Bundle/Seo/Controller/Redirect/CleanupController.php
  src/Bundle/Seo/Controller/Redirect/ExportController.php
  src/Bundle/Seo/Controller/Redirect/ImportController.php
  src/Bundle/Seo/Event/PreResponse/RedirectImportStatsEvent.php
  src/Bundle/Seo/Hydrator/RedirectImportStatsHydrator.php
  src/Bundle/Seo/Hydrator/RedirectImportStatsHydratorInterface.php
  src/Bundle/Seo/Repository/RedirectsRepository.php
  src/Bundle/Seo/Repository/RedirectsRepositoryInterface.php
  src/Bundle/Seo/Schema/RedirectImportStats.php
  src/Bundle/Seo/Service/CsvService.php
  src/Bundle/Seo/Service/CsvServiceInterface.php
  src/Bundle/Seo/Service/RedirectsService.php
  src/Bundle/Seo/Service/RedirectsServiceInterface.php
  src/Util/Constant/HttpResponseHeaders.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1186 [Redirects] Add endpoints for redirect options
  config/bundle_seo.yaml
  doc/05_Additional_Custom_Attributes.md
  src/Asset/Schema/Type/Video.php
  src/Bundle/Seo/Attribute/Content/PrioritiesJson.php
  src/Bundle/Seo/Attribute/Content/StatusesJson.php
  src/Bundle/Seo/Attribute/Content/TypesJson.php
  src/Bundle/Seo/Controller/Redirect/ListPrioritiesController.php
  src/Bundle/Seo/Controller/Redirect/ListStatusesController.php
  src/Bundle/Seo/Controller/Redirect/ListTypesController.php
  src/Bundle/Seo/Event/PreResponse/RedirectStatusEvent.php
  src/Bundle/Seo/Hydrator/RedirectStatusHydrator.php
  src/Bundle/Seo/Hydrator/RedirectStatusHydratorInterface.php
  src/Bundle/Seo/Schema/RedirectStatus.php
  src/Bundle/Seo/Service/RedirectsService.php
  src/Bundle/Seo/Service/RedirectsServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1192 [Reports] Add drill down functionality
  src/CustomReport/Attribute/Property/FilterProperty.php
  src/CustomReport/Attribute/Request/DrillDownRequestBody.php
  src/CustomReport/Controller/Chart/DrillDownOptionsController.php
  src/CustomReport/Controller/Chart/GetController.php
  src/CustomReport/Controller/Export/Csv/ExportController.php
  src/CustomReport/Event/DrillDownOptionEvent.php
  src/CustomReport/Hydrator/CustomReportHydrator.php
  src/CustomReport/Hydrator/CustomReportHydratorInterface.php
  src/CustomReport/MappedParameter/DrillDownParameter.php
  src/CustomReport/MappedParameter/FiltersParameter.php
  src/CustomReport/Repository/CustomReportRepository.php
  src/CustomReport/Schema/CustomReportColumnConfiguration.php
  src/CustomReport/Schema/CustomReportDrillDownOption.php
  src/CustomReport/Service/AdapterService.php
  src/CustomReport/Service/AdapterServiceInterface.php
  src/CustomReport/Service/CustomReportService.php
  src/CustomReport/Service/CustomReportServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#1196 [Advanced Columns] Fix Array nesting.
  src/Grid/Column/Collector/DataObject/AdvancedColumnCollector.php
Labels: Task

#1200 [Reports] Adapt Chart and export endpoints
  src/Bundle/CustomReport/Attribute/Request/ChartDataRequestBody.php
  src/Bundle/CustomReport/Attribute/Request/CsvExportRequestBody.php
  src/Bundle/CustomReport/Controller/Chart/GetController.php
  src/Bundle/CustomReport/Controller/Export/Csv/ExportController.php
  src/Bundle/CustomReport/Hydrator/CustomReportHydrator.php
  src/Bundle/CustomReport/MappedParameter/ChartDataParameter.php
  src/Bundle/CustomReport/MappedParameter/ExportParameter.php
  src/Bundle/CustomReport/Service/AdapterService.php
  src/Bundle/CustomReport/Service/AdapterServiceInterface.php
  src/Bundle/CustomReport/Service/CsvService.php
  src/Bundle/CustomReport/Service/CustomReportService.php
  src/Bundle/CustomReport/Service/CustomReportServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#1201 [Grid] Differentiate Data Object and Asset on Grid Configuration.
  src/Asset/Controller/Grid/Configuration/SaveConfigurationController.php
  src/Asset/Controller/Grid/Configuration/UpdateConfigurationController.php
  src/DataObject/Attribute/Property/SaveConfigurationColumn.php
  src/DataObject/Controller/Grid/Configuration/SaveConfigurationController.php
  src/DataObject/Controller/Grid/Configuration/UpdateConfigurationController.php
  src/DataObject/MappedParameter/ConfigurationParameter.php
  src/Grid/Attribute/Request/ConfigurationRequestBody.php
  src/Grid/MappedParameter/ConfigurationParameter.php
  src/Grid/MappedParameter/ConfigurationParameterInterface.php
  src/Grid/Schema/Column.php
  src/Grid/Schema/DetailedConfiguration.php
  src/Grid/Service/SaveConfigurationService.php
  src/Grid/Service/SaveConfigurationServiceInterface.php
Labels: Task

#1216 [Translation] Add Domain to Create/Delete/Update
  src/Translation/Controller/DeleteController.php
  src/Translation/Controller/ListController.php
  src/Translation/Repository/TranslationRepository.php
  src/Translation/Repository/TranslationRepositoryInterface.php
  src/Translation/Schema/CreateTranslationData.php
  src/Translation/Schema/TranslationData.php
  src/Translation/Service/TranslatorService.php
  src/Translation/Service/TranslatorServiceInterface.php
Labels: Task

#1220 [Translation] Add search filter
  src/Filter/FilterType.php
  src/Translation/Controller/ListController.php
  src/Translation/Repository/TranslationRepository.php
  src/Translation/Repository/TranslationRepositoryInterface.php
  src/Translation/Service/TranslatorService.php
  translations/studio_api_docs.en.yaml
Labels: Task

#1230 [Task] Fix Schema in LogEntry
  src/Bundle/ApplicationLogger/Schema/LogEntry.php
Labels: Task

#1229 [Advanced grid columns] Use DataObjectConfigurationParameter to update Data Object Configuration.
  src/DataObject/Controller/Grid/Configuration/UpdateConfigurationController.php
  src/Grid/Service/UpdateConfigurationService.php
  src/Grid/Service/UpdateConfigurationServiceInterface.php
Labels: Task

#1244 [Redirects] - Implemented search specific filter
  config/bundle_seo.yaml
  src/Bundle/Seo/Controller/Redirect/CollectionController.php
  src/Bundle/Seo/Filter/UrlFilter.php
  src/Bundle/Seo/Repository/RedirectsRepository.php
  src/Bundle/Seo/Service/FilterService.php
  src/Bundle/Seo/Service/FilterServiceInterface.php
  src/Listing/Service/ListingFilterInterface.php
Labels: Improvement
