Repository pimcore/studio-backend-bundle, pull requests merged in 2025-08, with the labels that each got.

#1252 [Listing]: Allow multiple filters of same type
  src/Element/ExecutionEngine/Util/JobSteps.php
  src/Filter/Mapper/CollectionParametersMapper.php
  src/Listing/Filter/EqualsFilter.php
  src/Listing/Filter/LikeFilter.php
Labels: Improvement

#1269 [Reports Editor] Add Create Custom report config endpoint
  src/Bundle/CustomReport/Controller/Config/AddController.php
  src/Bundle/CustomReport/Controller/Config/GetController.php
  src/Bundle/CustomReport/Hydrator/CustomReportHydrator.php
  src/Bundle/CustomReport/Repository/CustomReportRepository.php
  src/Bundle/CustomReport/Repository/CustomReportRepositoryInterface.php
  src/Bundle/CustomReport/Schema/CustomReportAdd.php
  src/Bundle/CustomReport/Schema/CustomReportDetails.php
  src/Bundle/CustomReport/Service/CustomReportService.php
  src/Bundle/CustomReport/Service/CustomReportServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1270 [Reports Editor] Add Update Custom report config endpoint
  src/Bundle/CustomReport/Controller/Config/UpdateController.php
  src/Bundle/CustomReport/Repository/CustomReportRepository.php
  src/Bundle/CustomReport/Repository/CustomReportRepositoryInterface.php
  src/Bundle/CustomReport/Schema/CustomReportUpdate.php
  src/Bundle/CustomReport/Service/AdapterService.php
  src/Bundle/CustomReport/Service/CustomReportService.php
  src/Bundle/CustomReport/Service/CustomReportServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1273 [User]: Add endpoints to list sharing lists
  src/Role/Controller/GetRolesWithPermissionController.php
  src/Role/MappedParameter/RolePermissionParameter.php
  src/Role/Repository/RoleRepository.php
  src/Role/Repository/RoleRepositoryInterface.php
  src/Role/Service/RoleService.php
  src/Role/Service/RoleServiceInterface.php
  src/User/Controller/GetUsersWithPermissionController.php
  src/User/MappedParameter/UserWithPermissionParameter.php
  src/User/Repository/UserRepository.php
  src/User/Repository/UserRepositoryInterface.php
  src/User/Schema/SimpleUser.php
  src/User/Service/UserService.php
  src/User/Service/UserServiceInterface.php
  src/Util/Constant/UserPermissions.php
  tests/Unit/User/Repository/UserRepositoryTest.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1283 [Assets]: Add option to force asset type check on upload
  src/Asset/Attribute/Property/AssetType.php
  src/Asset/Attribute/Property/FileUpload.php
  src/Asset/Controller/Upload/AddController.php
  src/Asset/Service/UploadService.php
  src/Asset/Service/UploadServiceInterface.php
Labels: Improvement

#1303 [Notifications Mercure event] - send Mercure event when a new notification is received
  config/notifications.yaml
  src/Notification/EventSubscriber/NotificationSavedSubscriber.php
  src/Notification/Hydrator/NotificationHydrator.php
  src/Notification/Hydrator/NotificationHydratorInterface.php
  src/Notification/Mercure/Events.php
  src/Notification/Mercure/Provider/NotificationTopicProvider.php
  src/Notification/Schema/NotificationMinimal.php
  src/Notification/Service/NotificationService.php
  src/Notification/Service/NotificationServiceInterface.php
Labels: New Feature

#1307 [Grid] List all Object Brick for Advanced Columns.
  config/object_brick.yaml
  src/Grid/Column/Collector/DataObject/AdvancedColumnCollector.php
  src/Grid/Column/Collector/DataObject/ObjectBrickCollector.php
  src/ObjectBrick/Service/ObjectBrickService.php
  src/ObjectBrick/Service/ObjectBrickServiceInterface.php
Labels: Task

#1319 [Grid] [Filter] Allow null on bool filter
  composer.json
  doc/03_Grid.md
  src/DataIndex/Filter/DataObject/BooleanFilter.php
  src/DataIndex/Query/DataObjectQuery.php
  src/DataIndex/Query/DataObjectQueryInterface.php
  src/Filter/MappedParameter/FilterParameter.php
Labels: Task

#1321 [Translations]: Add param to allow exceptions on duplicate creation of a translation key
  src/Translation/Controller/CreateController.php
  src/Translation/Repository/TranslationRepository.php
  src/Translation/Repository/TranslationRepositoryInterface.php
  src/Translation/Schema/CreateTranslation.php
  src/Translation/Service/TranslatorService.php
  src/Translation/Service/TranslatorServiceInterface.php
Labels: Improvement

#1326 [Grid] [Filter] Add localized fields to filter
  src/Filter/MappedParameter/FilterParameter.php
  src/Grid/Schema/Filter.php
  src/MappedParameter/Filter/ColumnFilter.php
Labels: Task
