Repository pimcore/studio-backend-bundle, pull requests merged in 2025-03, with the labels that each got.

#858 [Grid] [Data Objects] Advanced Columns Collector
  config/grid.yaml
  config/pimcore/config.yaml
  doc/10_Extending_Studio/05_Grid.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreStudioBackendExtension.php
  src/Grid/Column/Collector/DataObject/AdvancedColumnCollector.php
  src/Grid/Util/RelationField.php
  src/Grid/Util/SimpleField.php
Labels: Task

#861 [Task] Add parent node for locate in tree
  src/DataIndex/Query/TreeQuery.php
Labels: Task

#868 [Grid] [Data Object] Add Resolver for Objectbricks.
  config/grid.yaml
  src/Grid/Column/Collector/DataObject/FieldDefinitionCollector.php
  src/Grid/Column/Collector/DataObject/ObjectBrickCollector.php
  src/Grid/Column/Resolver/DataObject/ObjectBrickResolver.php
  src/Grid/Service/ColumnConfigurationService.php
  src/Grid/Service/ColumnConfigurationServiceInterface.php
  src/Grid/Util/ObjectBrickKey.php
Labels: Task

#872 [Grid] [Data Objects] make Group optional.
  src/Grid/Schema/Column.php
  src/Grid/Service/GridService.php
Labels: Bug

#875 [Task] Update cache after user save
  src/Security/Voter/UserPermissionVoter.php
  src/User/Service/UserUpdateService.php
  src/Util/Constant/CacheKeys.php
Labels: Task, Pimcore:ToDo

#880 [Task] Make default perspective available for everyone
  config/security.yaml
  src/Perspective/Controller/GetConfigurationController.php
  src/Security/Voter/UserPerspectiveVoter.php
  src/Util/Constant/PerspectivePermissions.php
Labels: Task, Pimcore:ToDo

#882 [Task] Return null if parent does not have field definition
  src/DataObject/Util/Trait/ValidateObjectDataTrait.php
Labels: Task, Pimcore:ToDo

#881 [Grid] [Data Objects] null when Object Brick not set.
  src/Grid/Column/Resolver/DataObject/ObjectBrickResolver.php
Labels: Bug

#883 [Grid] [Data Objects] Use original column key from request
  src/Grid/Column/Resolver/DataObject/ObjectBrickResolver.php
Labels: Bug

#887 [Grid] [Data Objects] Consider grid and search visibility options for default.
  config/pimcore/config.yaml
  src/Grid/Service/ConfigurationService.php
Labels: Task

#897 [Task] $iconPath can be null and empty.
  src/Icon/Service/IconService.php
Labels: Task, Pimcore:ToDo

#901 [Task] Adding published to manytoone relations
  src/DataObject/Data/Adapter/ManyToOneRelationAdapter.php
Labels: Task, Pimcore:ToDo

#904 [Task] Use save service
  src/DataObject/Service/DataObjectService.php
Labels: Task, Pimcore:ToDo

#905 [Search] [Assets] Search Endpoint
  config/grid.yaml
  src/Asset/Controller/Search/GetSearchResultController.php
  src/Filter/MappedParameter/FilterParameter.php
  src/Grid/Attribute/Request/SearchGridRequestBody.php
  src/Grid/MappedParameter/SearchGridParameter.php
  src/Grid/Service/GridSearchService.php
  src/Grid/Service/GridSearchServiceInterface.php
  src/Grid/Service/GridService.php
  src/Grid/Service/GridServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Task

#906 [Task] Fix loading of class with lower case ids
  src/DataObject/Service/DataObjectService.php
Labels: Task, Pimcore:ToDo

#913 Added allowed classes and allowed doctypes
  src/OpenApi/Schema/UserInformation.php
  src/User/Hydrator/UserInformationHydrator.php
Labels: Improvement

#917 [Data Object Editor] User select data type miss-match
  config/data_objects.yaml
  config/pimcore/config.yaml
  src/DataObject/Data/Adapter/UserAdapter.php
Labels: Task

#920 [Data Object Creation] Catch duplicate full path exception
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataObjectServiceInterface.php
Labels: Improvement

#927 [Perspectives] Integrate into user management
  config/pimcore/default_perspective.yaml
  config/users.yaml
  src/Element/Controller/GetIdByPathController.php
  src/Element/Service/ElementService.php
  src/Element/Service/ElementServiceInterface.php
  src/Entity/Perspective/UserPerspectiveData.php
  src/Installer.php
  src/OpenApi/Schema/UserInformation.php
  src/Perspective/Service/PerspectiveService.php
  src/Perspective/Service/PerspectiveServiceInterface.php
  src/Role/Hydrator/RoleHydrator.php
  src/Role/MappedParameter/UpdateRoleParameter.php
  src/Role/Schema/DetailedRole.php
  src/Role/Schema/UpdateRole.php
  src/Role/Service/RoleService.php
  src/Security/Voter/UserPerspectiveVoter.php
  src/User/Controller/UpdateActivePerspectiveController.php
  src/User/Hydrator/UserHydrator.php
  src/User/Hydrator/UserInformationHydrator.php
  src/User/MappedParameter/UpdateUserParameter.php
  src/User/Repository/PerspectiveRepository.php
  src/User/Repository/PerspectiveRepositoryInterface.php
  src/User/Schema/UpdateUser.php
  src/User/Schema/User.php
  src/User/Service/UpdateService.php
  src/User/Service/UpdateServiceInterface.php
  src/User/Service/UserPerspectiveService.php
  src/User/Service/UserPerspectiveServiceInterface.php
  src/User/Service/UserUpdateService.php
  src/User/Service/UserUpdateServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#933 [Task]: Change GDI requirement to support DBAL v4
  composer.json
Labels: Task, Pimcore:ToDo

#924 [Grid] [DataObject] Endpoint available classes for folder.
  config/class.yaml
  config/data_objects.yaml
  src/Class/Controller/Folder/CollectionController.php
  src/Class/Event/ClassDefinitionFolderListEvent.php
  src/Class/Hydrator/Folder/ClassDefinitionFolderItemHydrator.php
  src/Class/Hydrator/Folder/ClassDefinitionFolderItemHydratorInterface.php
  src/Class/Schema/Folder/ClassDefinitionFolderItem.php
  src/Class/Service/ClassDefinitionService.php
  src/Class/Service/ClassDefinitionServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: Improvement

#932 [Bug]: Remove cascade merge.
  src/Entity/Grid/GridConfiguration.php
  src/Entity/Grid/GridConfigurationFavorite.php
  src/Entity/Grid/GridConfigurationShare.php
Labels: Bug

#934 [Perspectives] Add permissions on install
  src/Installer.php
  src/Perspective/Controller/Widget/AddController.php
  src/Perspective/Controller/Widget/CollectionConfigurationController.php
  src/Perspective/Controller/Widget/DeleteController.php
  src/Perspective/Controller/Widget/GetConfigurationController.php
  src/Perspective/Controller/Widget/TypeController.php
  src/Perspective/Controller/Widget/UpdateController.php
  src/Util/Constant/UserPermissions.php
  translations/admin.en.yaml
Labels: Improvement

#936 [Composer]: Change GDI to 2.x-dev
  composer.json
Labels: Pimcore:Priority, Task

#935 [Perspectives] Add prefix for studio permissions
  src/Util/Constant/UserPermissions.php
  translations/admin.en.yaml
Labels: Task

#937 [Task] Creation date can be null
  src/Class/Schema/ClassDefinition.php
Labels: Task, Pimcore:ToDo

#939 [Task] Adding length, cannot be null
  src/Installer.php
Labels: Task, Pimcore:ToDo

#938 [Elements] Catch duplicate full path exception
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataObjectServiceInterface.php
  src/Element/Service/ElementFolderService.php
  src/Exception/Api/ElementExistsException.php
  src/Patcher/Adapter/KeyAdapter.php
  src/Patcher/Service/PatchService.php
  src/Updater/Service/UpdateService.php
  src/Util/Trait/ElementProviderTrait.php
Labels: Improvement

#945 [Bug] Use messageBus instead of eventDispatcher for messages
  src/Asset/Service/BinaryService.php
  src/Asset/Service/DocumentService.php
Labels: Bug

#940 [Improvement] Normalize HotspotImages
  src/DataObject/Data/Adapter/HotspotImageAdapter.php
Labels: Improvement

#948 [Tags][API] Remove and Apply Tags for Children does not work if there are no Tags applied
  src/Tag/Service/ExecutionEngine/BatchService.php
Labels: Task

#954 [Simple Search] Delete the "table" value
  src/DataObject/Data/Adapter/BlockAdapter.php
  src/DataObject/Data/Adapter/FieldCollectionsAdapter.php
  src/DataObject/Data/Adapter/TableAdapter.php
  src/DataObject/Service/DataService.php
Labels: Improvement

#960 [Task] Get collections for classification store
  config/classification_store.yaml
  src/ClassificationStore/Controller/GetCollectionController.php
  src/ClassificationStore/Event/CollectionEvent.php
  src/ClassificationStore/Hydrator/CollectionHydrator.php
  src/ClassificationStore/Hydrator/CollectionHydratorInterface.php
  src/ClassificationStore/MappedParameter/ListClassificationStoreParameter.php
  src/ClassificationStore/Repository/CollectionConfigRepository.php
  src/ClassificationStore/Repository/CollectionConfigRepositoryInterface.php
  src/ClassificationStore/Repository/CollectionRelationsRepository.php
  src/ClassificationStore/Repository/CollectionRelationsRepositoryInterface.php
  src/ClassificationStore/Schema/Collection.php
  src/ClassificationStore/Service/CollectionService.php
  src/ClassificationStore/Service/CollectionServiceInterface.php
  src/OpenApi/Attribute/Parameter/Query/IdParameter.php
  src/OpenApi/Config/Tags.php
  translations/studio_api_docs.en.yaml
Labels: Task

#958 Add default dummy value for JWT to ease installation
  README.md
  doc/00_Installation.md
  doc/02_Mercure_Setup.md
  src/DependencyInjection/Configuration.php
Labels: Improvement
