Repository pimcore/studio-backend-bundle, pull requests merged in 2025-05, with the labels that each got.

#1056 [Asset Grid] Change format of relation types
  src/DataIndex/Hydrator/DocumentHydrator.php
  src/Document/Schema/Document.php
  src/Grid/Column/Resolver/Metadata/AssetResolver.php
  src/Grid/Column/Resolver/Metadata/DataObjectResolver.php
  src/Grid/Column/Resolver/Metadata/DocumentResolver.php
Labels: Task

#1059 [Grid] [Objects] Publish column should be editable
  src/Grid/Column/Collector/DataObject/SystemFieldCollector.php
Labels: Task

#1066 [Grid] [Configuration] Make description nullable
  src/Entity/Grid/GridConfiguration.php
  src/Grid/MappedParameter/ConfigurationParameter.php
  src/Grid/MappedParameter/ConfigurationParameterInterface.php
  src/Grid/Schema/Configuration.php
  src/Installer.php
Labels: Bug

#1076 [Documents] Add missing document types
  config/data_index.yaml
  src/DataIndex/Hydrator/Document/EmailHydrator.php
  src/DataIndex/Hydrator/Document/EmailHydratorInterface.php
  src/DataIndex/Hydrator/Document/HardlinkHydrator.php
  src/DataIndex/Hydrator/Document/HardlinkHydratorInterface.php
  src/DataIndex/Hydrator/Document/LinkHydrator.php
  src/DataIndex/Hydrator/Document/LinkHydratorInterface.php
  src/DataIndex/Hydrator/Document/PageHydrator.php
  src/DataIndex/Hydrator/Document/PageHydratorInterface.php
  src/DataIndex/Hydrator/Document/SnippetHydrator.php
  src/DataIndex/Hydrator/Document/SnippetHydratorInterface.php
  src/DataIndex/Service/Hydrator/DocumentHydratorService.php
  src/DataIndex/Service/Hydrator/DocumentHydratorServiceInterface.php
  src/Document/Schema/Type/Email.php
  src/Document/Schema/Type/Hardlink.php
  src/Document/Schema/Type/Link.php
  src/Document/Schema/Type/Page.php
  src/Document/Schema/Type/Snippet.php
  src/Document/Service/HydratorService.php
  src/Document/Service/HydratorServiceInterface.php
  src/Document/Util/Trait/PageSnippetTrait.php
  src/Response/Schemas.php
Labels: New Feature

#1077 [Documents] Add tree endpoint
  config/documents.yaml
  src/DataIndex/Adapter/DocumentSearchAdapter.php
  src/DataIndex/Adapter/DocumentSearchAdapterInterface.php
  src/DataIndex/DocumentSearchResult.php
  src/DataIndex/Service/DocumentSearchService.php
  src/DataIndex/Service/DocumentSearchServiceInterface.php
  src/DataObject/Service/DataService.php
  src/Document/Attribute/Response/Property/AnyOfDocument.php
  src/Document/Controller/TreeController.php
  src/Document/Service/DataService.php
  src/Document/Service/DataServiceInterface.php
  src/Document/Service/DocumentService.php
  src/Document/Service/DocumentServiceInterface.php
  src/Factory/QueryFactory.php
  tests/Unit/Service/Factory/QueryFactoryTest.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1080 [Documents][Tree] Add Document
  composer.json
  config/documents.yaml
  src/Document/Attribute/Request/AddDocumentRequestBody.php
  src/Document/Controller/AddController.php
  src/Document/Event/DocumentDeleteEvent.php
  src/Document/Schema/DocumentAddParameters.php
  src/Document/Service/CreateService.php
  src/Document/Service/CreateServiceInterface.php
  src/Document/Service/DocumentService.php
  src/Document/Service/DocumentServiceInterface.php
  src/Element/Service/ElementDeleteService.php
  src/Util/Constant/Document/DocumentTypes.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1082 [Documents] Replace content
  config/documents.yaml
  src/Document/Controller/ReplaceController.php
  src/Document/Service/ReplaceService.php
  src/Document/Service/ReplaceServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1083 [Task] Context dot notation
  config/field_definition.yaml
  doc/10_Extending_Studio/10_Dot_Notation.md
  doc/10_Extending_Studio/README.md
  src/DependencyInjection/CompilerPass/FieldDefinitionResolverPass.php
  src/Exception/ParseException.php
  src/FieldDefinition/FieldDefinitionWrapper.php
  src/FieldDefinition/Parser/DotNotationParser.php
  src/FieldDefinition/Parser/DotNotationParserInterface.php
  src/FieldDefinition/Parser/ParseExeception.php
  src/FieldDefinition/Parser/Resolver/AbstractResolver.php
  src/FieldDefinition/Parser/Resolver/BlockResolver.php
  src/FieldDefinition/Parser/Resolver/DefaultResolver.php
  src/FieldDefinition/Parser/Resolver/FieldCollectionResolver.php
  src/FieldDefinition/Parser/Resolver/LocalizedFieldResolver.php
  src/FieldDefinition/Parser/Resolver/ObjectBrickResolver.php
  src/FieldDefinition/Parser/Resolver/ResolverInterface.php
  src/FieldDefinition/Service/Loader/TaggedIteratorResolverLoader.php
  src/FieldDefinition/Service/LocalizedFieldService.php
  src/FieldDefinition/Service/LocalizedFieldServiceInterface.php
  src/FieldDefinition/Service/ResolverLoaderInterface.php
  src/PimcoreStudioBackendBundle.php
Labels: Task

#1084 [Task] Use Dot Notation Parser for Path Formatter.
  config/data_objects.yaml
  src/DataObject/Attribute/Request/PathFormatterRequestBody.php
  src/DataObject/Legacy/PathFormatterHelper.php
  src/DataObject/Legacy/PathFormatterHelperInterface.php
  src/DataObject/MappedParameter/PathFormatterParameter.php
  src/DataObject/Service/PathFormatterService.php
Labels: Task

#1006 [Grid] [Data Object] Make classId and folderId optional my using query Parameter
  src/DataObject/Controller/Grid/GetAvailableColumnsController.php
  src/DataObject/MappedParameter/AvailableGridColumnParameter.php
  src/Grid/Service/ColumnConfigurationService.php
  src/Grid/Service/ColumnConfigurationServiceInterface.php
Labels: Task

#1088 [Docs] Fixed mercure configuration docs
  doc/00_Installation.md
  src/DependencyInjection/Configuration.php
  src/Mercure/Service/UrlService.php
Labels: Task

#1089 [Assets][Patch] Get type of new custom metadata
  src/Metadata/Patcher/Adapter/CustomMetadataAdapter.php
  src/Metadata/Service/DataResolverServiceInterface.php
  src/Metadata/Service/DataResolverServiceService.php
  src/Metadata/Updater/Adapter/CustomMetadataAdapter.php
Labels: Improvement

#1091 [Documents][Tree] Context menu add/update and remove site
  src/Document/Controller/Site/AvailableSitesController.php
  src/Document/Controller/Site/DeleteController.php
  src/Document/Controller/Site/UpdateController.php
  src/Document/Schema/DocumentAddParameters.php
  src/Document/Schema/DocumentCloneParameters.php
  src/Document/Schema/UpdateSiteParameters.php
  src/Document/Service/SiteService.php
  src/Document/Service/SiteServiceInterface.php
  src/Exception/Api/ElementSavingFailedException.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1092 [Documents][Tree] Convert document to different document ype
  config/documents.yaml
  src/Document/Controller/ConvertController.php
  src/Document/Service/CreateService.php
  src/Document/Service/ReplaceService.php
  src/Document/Service/ReplaceServiceInterface.php
  src/Document/Util/Trait/DocumentClassTrait.php
  src/Util/Constant/Document/NavigationProperties.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1096 [Bug] Fix Key Binding Hydration.
  src/User/Hydrator/KeyBindingHydrator.php
Labels: Bug

#1095 [Documents][Editor] List controllers and teplates
  config/documents.yaml
  doc/05_Additional_Custom_Attributes.md
  src/Document/Controller/PageSnippet/GetAvailableControllersController.php
  src/Document/Controller/PageSnippet/GetAvailableTemplatesController.php
  src/Document/Event/PreResponse/ControllerEvent.php
  src/Document/Event/PreResponse/TemplateEvent.php
  src/Document/Schema/PageSnippet/Controller.php
  src/Document/Schema/PageSnippet/Template.php
  src/Document/Schema/Site.php
  src/Document/Service/PageSnippetService.php
  src/Document/Service/PageSnippetServiceInterface.php
  src/Exception/Api/ReflectionException.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1099 Update PublicTranslations.php
  src/Util/Constant/PublicTranslations.php
Labels: Task

#1103 [Grid] [Advanced Columns] Add Static Text | Add Docs
  doc/03_Grid.md
  src/Grid/Column/Resolver/DataObject/AdvancedColumnResolver.php
  src/Grid/Schema/AdvancedColumnConfig/AdvancedColumnConfig.php
  src/Grid/Schema/AdvancedColumnConfig/StaticTextConfig.php
  src/Grid/Schema/Column.php
Labels: Task

#1109 [Translations] Only show public translation when not logged in.
  src/Security/Service/SecurityService.php
  src/Security/Service/SecurityServiceInterface.php
  src/Security/Voter/PublicAuthorizationVoter.php
  src/Translation/Service/TranslatorService.php
  tests/Unit/Service/Translator/TranslatorServiceTest.php
Labels: Bug

#1112 [Documents][Update]: add endpoint and logic for basic update
  doc/10_Extending_Studio/02_Documents/01_Document_types.md
  src/Document/Attribute/Request/UpdateDocumentRequestBody.php
  src/Document/Controller/UpdateController.php
  src/Document/Event/PreResponse/DocumentTypeSchemasEvent.php
  src/Document/Service/DataService.php
  src/Document/Service/DataServiceInterface.php
  src/OpenApi/Processor/AddDocumentTypeSchemaProcessor.php
  src/OpenApi/Service/OpenApiService.php
  src/Updater/Service/UpdateService.php
  src/Updater/Service/UpdateServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1119 [Document Types]: Add endpoints to delete and get types of DocTypes
  config/documents.yaml
  doc/05_Additional_Custom_Attributes.md
  src/Document/Controller/DocType/DeleteController.php
  src/Document/Controller/DocType/GetTypesController.php
  src/Document/Event/PreResponse/DocTypeTypeEvent.php
  src/Document/Hydrator/DocTypeTypeHydrator.php
  src/Document/Hydrator/DocTypeTypeHydratorInterface.php
  src/Document/Schema/DocTypeType.php
  src/Document/Service/DocTypeService.php
  src/Document/Service/DocTypeServiceInterface.php
  src/Exception/Api/DatabaseException.php
  translations/studio_api_docs.en.yaml
Labels: New Feature
