Repository pimcore/studio-backend-bundle, pull requests merged in 2025-09, with the labels that each got.

#1333 [Grid] Use base group for group check.
  src/Grid/Service/ConfigurationService.php
Labels: Task

#1334 [Document] Add Search
  src/DataIndex/Grid/GridSearch.php
  src/DataIndex/Grid/GridSearchInterface.php
  src/DataObject/Schema/DataObject.php
  src/Document/Schema/Document.php
  src/Grid/Column/Resolver/System/BooleanResolver.php
  src/Grid/Service/GridSearchService.php
  src/Grid/Service/GridSearchServiceInterface.php
  src/Grid/Service/GridService.php
  src/Grid/Service/GridServiceInterface.php
  src/Search/Controller/Document/GetSearchResultController.php
  translations/studio_api_docs.en.yaml
Labels: Task

#1340 [Grid] [Bug] Fix nested array
  src/Grid/Column/Collector/DataObject/ObjectBrickCollector.php
Labels: Bug

#1375 [Documents] Check pretty URL endpoint
  config/documents.yaml
  src/Document/Controller/Page/PrettyUrlController.php
  src/Document/Schema/CheckPrettyUrlParameters.php
  src/Document/Service/PageService.php
  src/Document/Service/PageServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1397 [Documents] Endpoint to fill the "edit site" form
  doc/05_Additional_Custom_Attributes.md
  src/Document/Controller/Site/GetController.php
  src/Document/Event/PreResponse/SiteDetailEvent.php
  src/Document/Hydrator/SiteHydrator.php
  src/Document/Hydrator/SiteHydratorInterface.php
  src/Document/Schema/SiteDetail.php
  src/Document/Service/HydratorService.php
  src/Document/Service/SiteService.php
  src/Document/Service/SiteServiceInterface.php
  translations/studio_api_docs.en.yaml
Labels: New Feature

#1398 [Grid] Add number Filter
  config/data_index_filters.yaml
  doc/03_Grid.md
  src/DataIndex/Filter/NumberFilter.php
  src/DataIndex/Query/AssetQuery.php
  src/DataIndex/Query/DataObjectQuery.php
  src/DataIndex/Query/DocumentQuery.php
  src/DataIndex/Query/QueryInterface.php
  src/Grid/Column/ColumnType.php
Labels: Task

#1410 [User management] granting permissions via role does not work
  src/Translation/Controller/AvailableLocalesController.php
  src/Translation/Controller/CreateController.php
  src/Translation/Repository/TranslationRepository.php
  src/Translation/Repository/TranslationRepositoryInterface.php
  src/User/Hydrator/UserInformationHydrator.php
  src/User/Service/UserPermissionService.php
  src/User/Service/UserPermissionServiceInterface.php
Labels: Improvement

#1396 [Object Tree] Handling of objects/variants
  doc/05_Additional_Custom_Attributes.md
  src/DataIndex/Adapter/DataObjectSearchAdapter.php
  src/DataIndex/Adapter/DataObjectSearchAdapterInterface.php
  src/DataIndex/Hydrator/DataObject/FolderHydrator.php
  src/DataIndex/Hydrator/DataObjectHydrator.php
  src/DataIndex/Hydrator/DataObjectHydratorInterface.php
  src/DataIndex/Query/DataObjectQuery.php
  src/DataIndex/Query/DataObjectQueryInterface.php
  src/DataIndex/Service/DataObjectSearchService.php
  src/DataIndex/Service/DataObjectSearchServiceInterface.php
  src/DataIndex/Service/Hydrator/DataObjectHydratorService.php
  src/DataIndex/Service/Hydrator/DataObjectHydratorServiceInterface.php
  src/DataObject/Attribute/Response/Property/AnyOfDataObjects.php
  src/DataObject/Event/PreResponse/DataObjectDetailEvent.php
  src/DataObject/Schema/DataObject.php
  src/DataObject/Schema/DataObjectDetail.php
  src/DataObject/Schema/Type/DataObjectFolder.php
  src/DataObject/Service/DataObjectService.php
  src/DataObject/Service/DataObjectServiceInterface.php
  src/DataObject/Service/DataService.php
  src/DataObject/Service/DataServiceInterface.php
  src/DataObject/Util/Trait/ClassDataTrait.php
  src/Response/Element.php
  src/Response/Schemas.php
  src/Version/Schema/DataObjectVersion.php
Labels: Improvement

#1426 Prepare Release for 0.9.30
  composer.json
  src/OpenApi/Config/Spec.php
Labels: Task
