Repository pimcore/studio-backend-bundle, pull requests merged in 2025-04, with the labels that each got.

#976 [Asset Editor] Image Preview issues
  public/img/tree-preview-transparent-background.png
  src/Asset/Service/ThumbnailService.php
Labels: Bug

#986 [Asset Metadata] Add metadata type to patcher schema
  src/Asset/Schema/PatchCustomMetadata.php
Labels: Improvement

#995 [Classification Store] Add search term
  config/classification_store.yaml
  src/ClassificationStore/Controller/GetCollectionsController.php
  src/ClassificationStore/Controller/GetGroupsController.php
  src/ClassificationStore/Controller/GetKeyGroupRelationsController.php
  src/ClassificationStore/MappedParameter/ListClassificationStoreParameter.php
  src/ClassificationStore/Repository/CollectionConfigRepository.php
  src/ClassificationStore/Repository/CollectionConfigRepositoryInterface.php
  src/ClassificationStore/Repository/GroupConfigRepository.php
  src/ClassificationStore/Repository/GroupConfigRepositoryInterface.php
  src/ClassificationStore/Repository/KeyGroupRelationRepository.php
  src/ClassificationStore/Repository/KeyGroupRelationRepositoryInterface.php
  src/ClassificationStore/Service/CollectionService.php
  src/ClassificationStore/Service/GroupService.php
  src/ClassificationStore/Service/KeyGroupRelationService.php
  src/ClassificationStore/Service/SearchHelperService.php
  src/ClassificationStore/Service/SearchHelperServiceInterface.php
  src/Translation/Repository/TranslationRepository.php
  src/Translation/Repository/TranslationRepositoryInterface.php
Labels: Task

#998 [Search] [Data Objects] Move Class ID to Mapped Param.
  src/Search/Controller/DataObject/GetConfigurationController.php
  src/Search/Controller/DataObject/GetSearchResultController.php
  src/Search/MappedParameter/ClassIdParameter.php
Labels: Task

#1001 [Translations] Allow creation of case-sensitive translation keys
  src/Installer.php
Labels: Bug

#1007 [ClassificationStore] Update QueryId Parameter to require object ID
  src/ClassificationStore/Controller/GetLayoutByCollectionController.php
  src/ClassificationStore/Controller/GetLayoutByGroupController.php
Labels: Bug

#1015 [Grid][Export] Improve User usage for collector
  src/DataObject/ExecutionEngine/AutomationAction/Messenger/Handler/ExportDataCollectionHandler.php
  src/Export/ExecutionEngine/AutomationAction/Messenger/Handler/CsvCreationHandler.php
  src/Export/ExecutionEngine/AutomationAction/Messenger/Handler/XlsxCreationHandler.php
  src/Export/Service/AbstractExportService.php
  src/Export/Service/ExportServiceInterface.php
Labels: Improvement

#1023 [Grid] Improve for extending the Grid.
  src/Exception/Api/NotFoundException.php
  src/Grid/Column/ClassIdInterface.php
  src/Grid/Column/ColumnType.php
  src/Grid/Column/Definition/DataObject/AbstractDefinition.php
  src/Grid/Schema/Column.php
  src/Grid/Schema/ColumnConfiguration.php
  src/Grid/Schema/ColumnData.php
  src/Grid/Util/Trait/ColumnDataTrait.php
  src/Grid/Util/Trait/Metadata/LocalizedValueTrait.php
  src/Response/StudioElementInterface.php
  src/Util/Constant/ElementTypes.php
Labels: Task

#1026 Add Product Registration
  .github/ci/files/config/packages/test/config.yaml
Labels: Task

#1027 [ClassificationStore] Add group ID's to collection endpoint
  src/ClassificationStore/Hydrator/CollectionHydrator.php
  src/ClassificationStore/Schema/Collection.php
Labels: Task

#1034 [Data Objects Editor] Delete autosave versions only after save
  src/Element/Service/ElementSaveService.php
  src/Patcher/Adapter/PublishAdapter.php
Labels: Improvement

#1038 [Docs] Update Docs
  doc/04_Generic_Execution_Engine.md
  doc/05_Additional_Custom_Attributes.md
  doc/07_User.md
  doc/10_Extending_Studio/01_Endpoints.md
  doc/10_Extending_Studio/02_Data_Objects/01_Field_Definition_adapters.md
  doc/10_Extending_Studio/02_OpenApi.md
  doc/10_Extending_Studio/03_Filters.md
  doc/10_Extending_Studio/04_Filters/01_Search_Index_Filters.md
  doc/10_Extending_Studio/05_Grid.md
  doc/10_Extending_Studio/06_Update_Patch.md
  doc/10_Extending_Studio/08_Events.md
  doc/10_Extending_Studio/README.md
  src/Updater/Service/Loader/TaggedIteratorAdapter.php
Labels: Task

#1046 [Task] Remove dev dependencies
  composer.json
Labels: Task
